"""
Extra exercises pack v2 — additional gym, cardio, core, running, stretching,
mobility and bodyweight variations. All entries have image_url, youtube_id,
instructions (>=2 steps), tips (>=1), muscle_group and muscle_region.
"""

# Shared images (Pexels/Unsplash, free license)
GYM_IMG = "https://images.pexels.com/photos/28080/pexels-photo.jpg"
BW_IMG = "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b"
RUN_IMG = "https://images.pexels.com/photos/2526878/pexels-photo-2526878.jpeg"
STRETCH_IMG = "https://images.pexels.com/photos/3823039/pexels-photo-3823039.jpeg"
CARDIO_IMG = "https://images.pexels.com/photos/4498572/pexels-photo-4498572.jpeg"


def _ex(id_, name, muscle, category, equipment, instructions, tips, region, yt, img=None):
    return {
        "id": id_,
        "name": name,
        "muscle_group": muscle,
        "muscle_region": region,
        "category": category,
        "equipment": equipment,
        "instructions": instructions,
        "tips": tips,
        "image_url": img or GYM_IMG,
        "youtube_id": yt,
    }


# ============================================================================
# GYM — 30 new exercises (chest, back, shoulders, arms, legs)
# ============================================================================
GYM_EXTRA = [
    # Chest variations
    _ex("ch-flexion-pike", "Flexiones Pike", "Hombro/Pecho", "gym", "Peso corporal",
        ["Posición de flexión con cadera elevada formando V invertida.",
         "Baja la cabeza hacia el suelo flexionando codos.",
         "Empuja fuerte para volver."],
        ["Trabaja hombros como press militar", "Progresión: elevar pies"], "chest", "b9X8fSPtKBs", BW_IMG),
    _ex("ch-flexion-archer", "Flexiones Archer", "Pecho", "gym", "Peso corporal",
        ["Manos abiertas amplio, palmas mirando al frente.",
         "Baja hacia un brazo estirando el otro.",
         "Sube y alterna."],
        ["Unilateral avanzado", "Trabaja un pecho a la vez"], "chest", "RE6wBSZUmXk", BW_IMG),
    _ex("ch-svend-press-disco", "Svend Press con Disco", "Pecho interno", "gym", "Disco",
        ["De pie, disco presionado entre las palmas al pecho.",
         "Aprieta fuerte y extiende brazos al frente.",
         "Vuelve lentamente."],
        ["Activa pecho interno", "Mantén tensión constante"], "chest", "GNL1sITBvO0"),
    _ex("ch-cable-crossover-bajo", "Cruce de Poleas (Bajo a Alto)", "Pecho superior", "gym", "Polea",
        ["Poleas en posición baja, cuerpo ligeramente inclinado.",
         "Lleva las manos de abajo hacia arriba cruzándolas al frente.",
         "Vuelve controlado."],
        ["Aisla pecho superior/clavicular", "No bajes los codos"], "chest", "taI4XduLpTk"),
    _ex("ch-press-guillotina", "Press Guillotina", "Pecho superior", "gym", "Barra",
        ["Tumbado en banco plano, barra con agarre ancho.",
         "Baja la barra al nivel del cuello (no al pecho).",
         "Empuja arriba."],
        ["Aislamiento extremo de clavicular", "Carga ligera, técnica impecable"], "chest", "BYKScL2sgCs"),
    # Back variations
    _ex("bk-pull-up-pesado", "Dominada con Peso", "Dorsal", "gym", "Cinturón con peso",
        ["Cinturón con disco colgando entre las piernas.",
         "Dominada clásica, barbilla sobre la barra.",
         "Baja controlado."],
        ["Progresión avanzada", "Core apretado"], "back", "eGo4IYlbE5g"),
    _ex("bk-meadows-row", "Meadows Row", "Dorsal", "gym", "Landmine",
        ["Agarra el extremo de una barra en landmine.",
         "Postura lateral, agarre neutro con la mano de ese lado.",
         "Rema llevando el codo al cuerpo."],
        ["Gran rango y contracción", "Torso firme"], "back", "mzLxBNuTM34"),
    _ex("bk-remo-gorilla", "Remo Gorila", "Dorsal", "gym", "Kettlebell",
        ["Dos kettlebells en el suelo.",
         "Alterna remos explosivos levantando uno a cada lado.",
         "Mantén cadera estable."],
        ["Quema intensa", "Ritmo rápido alternado"], "back", "X1UfBGwj2O0"),
    _ex("bk-straight-arm-pulldown", "Pulldown Brazos Rectos", "Dorsal", "gym", "Polea",
        ["Polea alta, brazos estirados al frente.",
         "Baja la barra hasta los muslos manteniendo codos fijos.",
         "Vuelve controlado."],
        ["Aísla dorsal sin implicar bíceps", "Aprieta dorsal abajo"], "back", "kiuVA0gs3EI"),
    _ex("bk-deadlift-sumo", "Peso Muerto Sumo", "Piernas/Espalda", "gym", "Barra",
        ["Postura amplia, dedos hacia fuera, barra cerca.",
         "Espalda neutra, agarre mixto o doble prono.",
         "Extiende caderas y rodillas a la vez."],
        ["Menos tensión lumbar", "Glúteos y aductores protagonistas"], "back", "wYREQkVtvEc"),
    # Shoulders
    _ex("sh-cable-lateral-raise", "Elevación Lateral en Polea", "Hombro medio", "gym", "Polea",
        ["Polea baja, coge el agarre con la mano opuesta.",
         "Eleva el brazo hasta paralelo al suelo.",
         "Baja controlado."],
        ["Tensión constante", "Controla el descenso"], "shoulders", "0tn5K9NlCfo"),
    _ex("sh-press-landmine", "Press Landmine Pie", "Hombro frontal", "gym", "Landmine",
        ["De rodillas o de pie frente a landmine.",
         "Empuja la barra hacia arriba en diagonal.",
         "Baja controlado."],
        ["Seguro para hombro", "Ángulo natural"], "shoulders", "YKZVS8hGaeI"),
    _ex("sh-cuban-press", "Press Cubano", "Manguito rotador/Hombro", "gym", "Mancuernas",
        ["Mancuernas a los lados.",
         "Remo al mentón, rotación externa, press.",
         "Invertir para bajar."],
        ["Calentamiento perfecto", "Cargas muy ligeras"], "shoulders", "eEQYc73aFyU"),
    # Biceps
    _ex("bi-curl-spider", "Curl Spider", "Bíceps", "gym", "Mancuernas",
        ["Tumbado boca abajo en banco inclinado.",
         "Brazos colgando rectos hacia abajo.",
         "Curl contrayendo sin momentum."],
        ["Aísla bíceps corto", "Rango completo"], "upper arms", "qCRdghIaQc0"),
    _ex("bi-curl-arrastre", "Curl Arrastre (Drag)", "Bíceps", "gym", "Barra",
        ["Barra al frente, pegada al cuerpo.",
         "Curl arrastrando la barra por el abdomen.",
         "Codos van atrás."],
        ["Aísla cabeza larga", "Cuerpo estable"], "upper arms", "_I9Hq0fB_r4"),
    _ex("bi-curl-incline", "Curl Inclinado Mancuernas", "Bíceps cabeza larga", "gym", "Mancuernas",
        ["Banco inclinado 45-60°.",
         "Mancuernas colgando con palmas al frente.",
         "Curl controlado."],
        ["Estira la cabeza larga", "No balancees"], "upper arms", "soxrZlIl35U"),
    # Triceps
    _ex("tr-extension-mancuerna-vertical", "Extensión Francesa de Pie", "Tríceps cabeza larga", "gym", "Mancuerna",
        ["De pie, mancuerna con ambas manos sobre la cabeza.",
         "Baja detrás de la cabeza flexionando codos.",
         "Extiende hacia arriba."],
        ["Cabeza larga estirada", "Codos pegados a la cabeza"], "upper arms", "YbX7Wd8jQ-Q"),
    _ex("tr-diamond-pushup", "Flexión Diamante", "Tríceps", "gym", "Peso corporal",
        ["Manos juntas formando un diamante.",
         "Baja el pecho hacia las manos.",
         "Empuja."],
        ["Máxima activación tríceps", "Core apretado"], "upper arms", "J0DnG1_S92I", BW_IMG),
    _ex("tr-jm-press", "JM Press", "Tríceps", "gym", "Barra",
        ["Tumbado en banco, barra con agarre cerrado.",
         "Baja la barra hacia la garganta/clavícula manteniendo codos cerca.",
         "Empuja explosivo."],
        ["Híbrido press-skull crusher", "Avanzado"], "upper arms", "QOnqZjYHwYA"),
    # Legs
    _ex("le-sentadilla-pistol", "Sentadilla Pistol", "Cuádriceps/Core", "gym", "Peso corporal",
        ["De pie sobre una pierna, otra extendida al frente.",
         "Baja hasta sentadilla completa.",
         "Sube sin apoyar la otra pierna."],
        ["Fuerza unilateral avanzada", "Equilibrio clave"], "upper legs", "qDcniqddTeE", BW_IMG),
    _ex("le-sentadilla-zercher", "Sentadilla Zercher", "Cuádriceps/Core", "gym", "Barra",
        ["Barra apoyada en la flexura de los codos.",
         "Sentadilla profunda manteniendo torso erguido.",
         "Sube."],
        ["Activa core brutal", "Protege columna"], "upper legs", "EJBA0PmZeI4"),
    _ex("le-walking-lunge", "Zancada Andando", "Piernas/Glúteo", "gym", "Mancuernas",
        ["Mancuernas a los lados.",
         "Avanza paso largo alternando piernas.",
         "Recorre distancia objetivo."],
        ["Funcional", "Cuida rodilla delantera"], "upper legs", "L8fvypPrzzs"),
    _ex("le-step-up-alto", "Step-up Alto", "Cuádriceps/Glúteo", "gym", "Cajón alto",
        ["Cajón alto (rodilla en ángulo <90º).",
         "Sube con una pierna apretando glúteo arriba.",
         "Baja controlado."],
        ["Unilateral potente", "No uses impulso"], "upper legs", "dQqApCGd5Ss"),
    _ex("le-nordic-curl", "Nordic Hamstring Curl", "Femoral", "gym", "Peso corporal",
        ["Rodillas en suelo, tobillos fijados.",
         "Baja el torso hacia delante resistiendo con femorales.",
         "Empuja con manos si no puedes subir."],
        ["Máxima excéntrica femoral", "Progresa en semanas"], "upper legs", "w1djqMvs9W0", BW_IMG),
    _ex("le-cossack-squat", "Sentadilla Cossack", "Aductores/Cuádriceps", "gym", "Peso corporal",
        ["Postura muy ancha.",
         "Baja hacia un lado flexionando esa rodilla.",
         "La otra pierna se extiende."],
        ["Movilidad y fuerza", "Control total"], "upper legs", "TcY5Cgk9RYg", BW_IMG),
    _ex("le-jefferson-squat", "Sentadilla Jefferson", "Piernas/Glúteo", "gym", "Barra",
        ["Postura de piernas en tijera con barra entre ellas.",
         "Agarre mixto.",
         "Sentadilla con barra centrada."],
        ["Variante old-school", "Extraña pero muy efectiva"], "upper legs", "a3adoNQVQ1U"),
    # Calves & glutes
    _ex("le-calf-single-leg", "Gemelo a 1 Pierna", "Gemelos", "gym", "Peso corporal",
        ["De pie sobre un pie en un escalón.",
         "Eleva el talón máximo.",
         "Baja por debajo del escalón."],
        ["Unilateral", "Rango completo"], "lower legs", "-M4-G8p8fmc", BW_IMG),
    _ex("gl-kickback-polea", "Patada de Glúteo en Polea", "Glúteo", "gym", "Polea",
        ["Tobillo en polea baja.",
         "Extiende la pierna hacia atrás sin arquear lumbar.",
         "Vuelve controlado."],
        ["Aísla glúteo", "Aprieta arriba"], "upper legs", "6tX5lVSKa_Y"),
    _ex("gl-abductor-maquina", "Abductor en Máquina", "Glúteo medio", "gym", "Máquina",
        ["Sentado en máquina de abductores.",
         "Separa las piernas empujando las almohadillas.",
         "Vuelve controlado."],
        ["Aísla glúteo medio", "Carga progresiva"], "upper legs", "kC1MvK1YqEM"),
    _ex("gl-rdl-sl", "RDL a 1 Pierna", "Femoral/Glúteo", "gym", "Mancuerna",
        ["Mancuerna en una mano, pierna opuesta como apoyo.",
         "Inclínate al frente con la otra pierna extendida atrás.",
         "Vuelve apretando glúteo."],
        ["Equilibrio + fuerza", "Cadera cuadrada"], "upper legs", "Xrve9E8Bf5w"),
]


# ============================================================================
# CORE / ABDOMEN — 15 new exercises
# ============================================================================
CORE_EXTRA = [
    _ex("co-plank-up-down", "Plancha Up-Down", "Core", "gym", "Peso corporal",
        ["Plancha alta con manos.",
         "Baja a antebrazo derecho, izquierdo.",
         "Sube al plano inicial y repite."],
        ["Dinámico", "Cadera estable"], "core", "QLgYsNgwq_w", BW_IMG),
    _ex("co-plank-tocar-hombro", "Plancha Tocar Hombro", "Core anti-rotación", "gym", "Peso corporal",
        ["Plancha alta.",
         "Toca el hombro opuesto con una mano.",
         "Alterna evitando rotación."],
        ["Anti-rotación pura", "Cadera fija"], "core", "CxenTrlFK_A", BW_IMG),
    _ex("co-hollow-rock", "Hollow Rock", "Core", "gym", "Peso corporal",
        ["Posición hollow (cuerpo en C invertida).",
         "Mécete adelante y atrás sin perder tensión.",
         "Lumbar pegada al suelo."],
        ["Gimnasia deportiva", "Avanzado"], "core", "LlDNef_Ztsc", BW_IMG),
    _ex("co-toe-touch", "Toe Touch", "Abdomen", "gym", "Peso corporal",
        ["Tumbado boca arriba, piernas verticales.",
         "Eleva torso y toca los pies con las manos.",
         "Baja sin apoyar cabeza."],
        ["Recto abdominal alto", "Sin impulso"], "core", "U4s4mEQ5VqU", BW_IMG),
    _ex("co-knee-tuck-bench", "Knee Tuck en Banco", "Abdomen bajo", "gym", "Banco",
        ["Sentado al borde del banco, apoyo en manos atrás.",
         "Extiende piernas al frente y flexiona rodillas al pecho.",
         "Alterna sin pausa."],
        ["Abs bajo + core", "Controla velocidad"], "core", "Y9uGqmCNb_U"),
    _ex("co-around-world", "Around the World", "Core/Oblicuos", "gym", "Disco",
        ["De pie, disco con ambas manos sobre la cabeza.",
         "Gira el disco alrededor del cuerpo.",
         "Cambia de dirección."],
        ["Core global", "Carga ligera"], "core", "UwM1j6CSxMI"),
    _ex("co-plank-reach", "Plancha con Extensión", "Core anti-rotación", "gym", "Peso corporal",
        ["Plancha alta.",
         "Extiende un brazo al frente tocando una referencia.",
         "Alterna."],
        ["Desafío anti-rotación", "Cadera nivelada"], "core", "xBfxmwm3CwE", BW_IMG),
    _ex("co-dragon-flag-bent", "Dragon Flag (Rodillas)", "Core", "gym", "Banco",
        ["Tumbado en banco, manos agarran detrás de la cabeza.",
         "Eleva piernas con rodillas flexionadas rectas.",
         "Baja controlado."],
        ["Progresión a Dragon Flag", "Muy exigente"], "core", "PBhZsM05y6Y"),
    _ex("co-farmer-carry", "Paseo del Granjero", "Core/Antebrazo", "gym", "Mancuernas",
        ["Dos mancuernas pesadas a los lados.",
         "Camina en línea recta, pasos cortos, hombros altos.",
         "Aguanta la distancia objetivo."],
        ["Funcional total", "Cuerpo erguido"], "core", "rt17lmnaLSM"),
    _ex("co-suitcase-carry", "Suitcase Carry", "Oblicuos", "gym", "Mancuerna",
        ["Una sola mancuerna pesada en una mano.",
         "Camina recto sin inclinarte al lado.",
         "Cambia de lado."],
        ["Anti-flexión lateral", "Oblicuos brutales"], "core", "A_gjLUq6JLM"),
    _ex("co-pallof-banda", "Pallof Press con Banda", "Core anti-rotación", "gym", "Banda",
        ["Banda lateral anclada.",
         "Empuja al frente manteniendo core firme.",
         "Vuelve controlado."],
        ["Estabilidad central", "Cuerpo cuadrado"], "core", "AH_QZLm_0-s"),
    _ex("co-medicine-slam", "Medicine Ball Slam", "Core explosivo", "gym", "Pelota medicinal",
        ["De pie, pelota sobre la cabeza.",
         "Lanza con fuerza al suelo.",
         "Recoge y repite."],
        ["Explosividad + core", "Buena válvula de descarga"], "core", "eITiwa7zFx4"),
    _ex("co-sit-up-v", "V-Up Completo", "Abdomen", "gym", "Peso corporal",
        ["Tumbado brazos/piernas extendidos.",
         "Eleva tronco y piernas simultáneamente tocando los dedos.",
         "Baja."],
        ["Abdomen completo", "Avanzado"], "core", "iP5UZf2arAQ", BW_IMG),
    _ex("co-scissor-kicks", "Tijeras", "Abdomen bajo", "gym", "Peso corporal",
        ["Tumbado piernas extendidas a 20°.",
         "Cruza piernas alternando arriba/abajo.",
         "Lumbar pegada al suelo."],
        ["Abdomen inferior", "Aguante"], "core", "XYd_Ps4Y3l4", BW_IMG),
    _ex("co-rotational-chop", "Chop Rotacional en Polea", "Oblicuos", "gym", "Polea",
        ["Polea alta un lado.",
         "Cruza el torso bajando la cuerda en diagonal.",
         "Vuelve controlado."],
        ["Funcional oblicuos", "Rotación potente"], "core", "iSnzBppXVWE"),
]


# ============================================================================
# RUNNING / CARDIO — 12 new blocks
# ============================================================================
CARDIO_EXTRA = [
    _ex("run-fartlek-basico", "Fartlek 30 min", "Cardio", "correr", "Peso corporal",
        ["Calienta 5 min trote suave.",
         "Alterna 2 min rápido / 2 min suave durante 20 min.",
         "Enfría 5 min."],
        ["Mejora resistencia anaeróbica", "Escucha tu cuerpo"], "cardio", "5zmdPnY1ptM", RUN_IMG),
    _ex("run-intervalos-400", "Intervalos 400m", "Cardio", "correr", "Peso corporal",
        ["Calienta 10 min.",
         "8 x 400m a ritmo rápido con 90s descanso entre series.",
         "Enfría 10 min suave."],
        ["Mejora VO2max", "Recuperación activa caminando"], "cardio", "KiGBZCyZlws", RUN_IMG),
    _ex("run-tempo-20min", "Tempo Run 20 min", "Cardio", "correr", "Peso corporal",
        ["Calienta 10 min trote.",
         "20 min a ritmo medio-alto (umbral).",
         "Enfría 10 min."],
        ["Mejora umbral lactato", "Ritmo controlado"], "cardio", "ZvgOLxSG9oM", RUN_IMG),
    _ex("run-escalera", "Sprints en Escaleras", "Cardio", "correr", "Peso corporal",
        ["Calienta 5 min.",
         "10 subidas rápidas con bajada caminando.",
         "Enfría 5 min."],
        ["Fuerza + cardio", "Rodillas altas"], "cardio", "DfGHnUEPZ74", RUN_IMG),
    _ex("cardio-jumping-jacks", "Jumping Jacks", "Cardio", "correr", "Peso corporal",
        ["De pie, pies juntos, brazos pegados.",
         "Salta abriendo piernas y subiendo brazos.",
         "Vuelve y repite rápido."],
        ["Calentamiento clásico", "Ritmo sostenido"], "cardio", "c4DAnQ6DtF8", CARDIO_IMG),
    _ex("cardio-high-knees", "Skipping Alto", "Cardio", "correr", "Peso corporal",
        ["En el sitio.",
         "Alterna rodillas al pecho con brazos coordinados.",
         "Ritmo rápido."],
        ["Activación total", "Core firme"], "cardio", "ZZZoCNMU48U", CARDIO_IMG),
    _ex("cardio-butt-kicks", "Talones al Glúteo", "Cardio", "correr", "Peso corporal",
        ["En el sitio.",
         "Lleva talones a los glúteos rápido.",
         "Brazos como corriendo."],
        ["Calentamiento específico corredor", "Cadera estable"], "cardio", "aajhW7DD1EA", CARDIO_IMG),
    _ex("cardio-step-touch", "Step Touch Explosivo", "Cardio", "correr", "Peso corporal",
        ["De pie.",
         "Da dos pasos laterales rápidos a cada lado.",
         "Brazos acompañan."],
        ["Bajo impacto", "Ritmo continuo"], "cardio", "KhBmA_nQjI4", CARDIO_IMG),
    _ex("cardio-burpee-medio", "Medio Burpee", "Cardio", "correr", "Peso corporal",
        ["Desde plancha.",
         "Salta trayendo pies cerca de manos.",
         "Vuelve a plancha y repite."],
        ["Versión menos impacto", "Ritmo constante"], "cardio", "TU8QYVW0gDU", CARDIO_IMG),
    _ex("cardio-tabata-4min", "Tabata 4 min", "Cardio HIIT", "correr", "Peso corporal",
        ["20s al máximo, 10s descanso.",
         "Repite 8 rondas (4 min total).",
         "Usa burpees o jumping jacks."],
        ["Protocolo clásico", "Intensidad total"], "cardio", "XIeCMhNWFQQ", CARDIO_IMG),
    _ex("cardio-bici-hiit", "HIIT en Bici Estática", "Cardio", "correr", "Bicicleta estática",
        ["Calentamiento 5 min suave.",
         "10 x (30s sprint + 60s suave).",
         "Enfría 5 min."],
        ["Bajo impacto rodilla", "Alta intensidad"], "cardio", "uhpAZn5Nnf0", CARDIO_IMG),
    _ex("cardio-remo-hiit", "HIIT Remo 15 min", "Cardio", "correr", "Remo",
        ["Calentamiento 3 min.",
         "10 x (30s fuerte + 30s suave).",
         "Enfría 3 min."],
        ["Trabajo completo", "Técnica antes que velocidad"], "cardio", "H0r_ZPXJLtg", CARDIO_IMG),
]


# ============================================================================
# STRETCHING / MOBILITY — 15 new exercises
# ============================================================================
STRETCH_EXTRA = [
    _ex("st-couch-stretch", "Couch Stretch", "Cuádriceps/Cadera", "estiramientos", "Pared",
        ["De rodillas frente a una pared, un pie contra pared.",
         "La otra pierna adelante con rodilla a 90°.",
         "Aguanta 60s, cambia."],
        ["Libera psoas y cuádriceps", "Odiarás al principio"], "cuadriceps", "vtt3e9Uev7Y", STRETCH_IMG),
    _ex("st-pigeon-pose", "Postura de la Paloma", "Glúteo/Piriforme", "estiramientos", "Esterilla",
        ["Pierna delantera flexionada en L, trasera estirada.",
         "Inclínate al frente respirando profundo.",
         "Aguanta 60s por lado."],
        ["Abre glúteos y caderas", "Relaja"], "core", "oX6I9nJYKP0", STRETCH_IMG),
    _ex("st-cobra-stretch", "Estiramiento Cobra", "Abdomen/Flexores", "estiramientos", "Esterilla",
        ["Tumbado boca abajo, manos bajo hombros.",
         "Estira brazos despegando el pecho.",
         "Mantén cadera pegada al suelo."],
        ["Abre parte anterior", "Respira"], "core", "eFuu9GA1amM", STRETCH_IMG),
    _ex("st-child-pose", "Postura del Niño", "Espalda baja", "estiramientos", "Esterilla",
        ["De rodillas, glúteos hacia los talones.",
         "Extiende brazos al frente, frente en suelo.",
         "Relaja 60s."],
        ["Descompresión vertebral", "Meditación"], "back", "eqVMAPM00DM", STRETCH_IMG),
    _ex("st-downward-dog", "Perro Boca Abajo", "Isquios/Espalda", "estiramientos", "Esterilla",
        ["Posición V invertida.",
         "Empuja el suelo con manos, talones bajo.",
         "Aguanta 45s."],
        ["Postura clásica yoga", "Alarga columna"], "back", "BF_ylSl6W7U", STRETCH_IMG),
    _ex("st-world-greatest", "World's Greatest Stretch", "Cadera/Torácica", "estiramientos", "Esterilla",
        ["Zancada profunda con la pierna delantera.",
         "Apoya mano contraria y rota el torso.",
         "Cambia de lado."],
        ["El mejor estiramiento único", "Móvilidad global"], "core", "KhumM1wjQdw", STRETCH_IMG),
    _ex("st-lizard-pose", "Postura del Lagarto", "Cadera/Aductores", "estiramientos", "Esterilla",
        ["Zancada profunda con ambas manos al interior de la pierna delantera.",
         "Baja el pecho hacia el suelo.",
         "60s por lado."],
        ["Abre cadera lateral", "Profundo"], "core", "6GMKPQVERzw", STRETCH_IMG),
    _ex("st-seated-forward-fold", "Flexión Sentado", "Isquios", "estiramientos", "Esterilla",
        ["Sentado con piernas extendidas.",
         "Inclínate al frente alcanzando los pies.",
         "Relaja la espalda, no fuerces."],
        ["Isquios profundos", "Respira hondo"], "hamstring", "XKc9hL-wvsw", STRETCH_IMG),
    _ex("st-butterfly-stretch", "Mariposa", "Aductores", "estiramientos", "Esterilla",
        ["Sentado, planta de pies juntas.",
         "Baja rodillas suavemente hacia el suelo.",
         "Inclínate al frente si puedes."],
        ["Aductores e ingle", "Sin rebotes"], "upper legs", "KcHjNP__q_o", STRETCH_IMG),
    _ex("st-spinal-twist", "Twist Espinal Supino", "Columna/Oblicuos", "estiramientos", "Esterilla",
        ["Tumbado boca arriba.",
         "Cruza una pierna al lado opuesto.",
         "Mirada al brazo opuesto. 45s por lado."],
        ["Movilidad torácica", "Relajante"], "core", "PEnDE7lKb4E", STRETCH_IMG),
    _ex("st-calf-stretch", "Estiramiento Gemelo", "Gemelos", "estiramientos", "Pared",
        ["De pie frente a pared.",
         "Un pie atrás con talón pegado al suelo.",
         "Adelanta cadera, 45s por lado."],
        ["Alivia sobrecarga", "Rodilla trasera recta"], "lower legs", "Wv6nVjjvVqg", STRETCH_IMG),
    _ex("st-wall-angels", "Wall Angels", "Movilidad torácica", "estiramientos", "Pared",
        ["Espalda pegada a pared, brazos en W.",
         "Sube brazos arriba sin despegarlos.",
         "Vuelve."],
        ["Movilidad torácica", "Corrige postura"], "shoulders", "1utOWAPD9lg", STRETCH_IMG),
    _ex("mo-cat-cow", "Gato-Vaca", "Columna", "movilidad", "Esterilla",
        ["Posición cuadrupedia.",
         "Alterna arquear columna (vaca) y redondear (gato).",
         "Ritmo con respiración."],
        ["Movilidad global columna", "Calentamiento básico"], "back", "kqnua4rHVVA", STRETCH_IMG),
    _ex("mo-thoracic-rotation", "Rotación Torácica", "Torácica", "movilidad", "Esterilla",
        ["Cuadrupedia, una mano en la nuca.",
         "Rota el codo al techo y luego cruza bajo el otro brazo.",
         "10 por lado."],
        ["Apertura torácica", "Movimiento fluido"], "back", "XPPfnSEATJA", STRETCH_IMG),
    _ex("mo-90-90-hip", "90-90 Cadera", "Cadera", "movilidad", "Esterilla",
        ["Sentado con ambas rodillas a 90°.",
         "Rota de un lado a otro moviendo las caderas.",
         "Inclínate al frente para intensificar."],
        ["Abre cadera en todos los planos", "Esencial para corredores"], "core", "LLp2f87Yrgc", STRETCH_IMG),
]


# ============================================================================
# BODYWEIGHT / HOME — 8 new exercises
# ============================================================================
BW_EXTRA = [
    _ex("bw-lunge-atras", "Zancada Atrás", "Piernas", "gym", "Peso corporal",
        ["De pie. Da un paso largo hacia atrás.",
         "Baja rodilla trasera cerca del suelo.",
         "Vuelve y alterna."],
        ["Más amigable para rodilla", "Core estable"], "upper legs", "2z8JmcrW-As", BW_IMG),
    _ex("bw-squat-jump", "Sentadilla con Salto", "Piernas explosivas", "gym", "Peso corporal",
        ["Sentadilla profunda.",
         "Sube explosivo saltando verticalmente.",
         "Aterriza suave y repite."],
        ["Potencia + cardio", "Amortigua rodillas"], "upper legs", "YziLy4dDi6w", BW_IMG),
    _ex("bw-burpee-completo", "Burpee Completo", "Cuerpo completo", "gym", "Peso corporal",
        ["De pie → plancha con salto.",
         "Flexión en plancha.",
         "Salto al frente + salto vertical."],
        ["Full body", "Intensidad máxima"], "core", "auBLPXO8Fww", BW_IMG),
    _ex("bw-inchworm", "Inchworm (Oruga)", "Core/Flexibilidad", "gym", "Peso corporal",
        ["De pie. Manos al suelo.",
         "Camina con las manos hacia plancha.",
         "Vuelve con las manos a los pies."],
        ["Movilidad + core", "Calentamiento top"], "core", "qqIsQ3t4XVM", BW_IMG),
    _ex("bw-bear-crawl", "Andar del Oso", "Core/Hombros", "gym", "Peso corporal",
        ["Cuadrupedia con rodillas levantadas.",
         "Camina adelante moviendo mano y pie opuestos.",
         "Mantén cadera baja."],
        ["Core anti-rotación", "Funcional"], "core", "0p_XHQQiWgg", BW_IMG),
    _ex("bw-superman-hold", "Superman Hold", "Espalda baja/Glúteos", "gym", "Peso corporal",
        ["Tumbado boca abajo, brazos extendidos al frente.",
         "Eleva brazos, pecho y piernas.",
         "Aguanta 20-30s."],
        ["Refuerza lumbar", "No arquees excesivo"], "back", "cc6UVRS7PW4", BW_IMG),
    _ex("bw-wall-sit", "Sentadilla Isométrica", "Cuádriceps", "gym", "Pared",
        ["Espalda pegada a pared.",
         "Baja a 90°, muslos paralelos al suelo.",
         "Aguanta 30-60s."],
        ["Resistencia muscular", "Aumenta tiempo progresivamente"], "upper legs", "y-wV4Venusw", BW_IMG),
    _ex("bw-glute-bridge-pulses", "Pulsos de Puente de Glúteo", "Glúteo", "gym", "Peso corporal",
        ["Puente de glúteo arriba.",
         "Pequeños pulsos manteniendo la cadera alta.",
         "20-30 pulsos por serie."],
        ["Quema brutal de glúteo", "Sin bajar cadera"], "upper legs", "Fw4i7iDh2Y0", BW_IMG),
]


# ============================================================================
# EXPORT — all extra exercises
# ============================================================================
EXTRA_V2 = GYM_EXTRA + CORE_EXTRA + CARDIO_EXTRA + STRETCH_EXTRA + BW_EXTRA
