"""Comprehensive GYM exercise library — Full coverage by muscle group.
Each exercise has instructions (4 steps), tips (2), image, YouTube demo video.
Category="gym" for all entries.
"""

from exercises_data import IMG

def _g(eid, name, mg, eq, instr, tips, img_key, yt=""):
    return {"id": eid, "name": name, "muscle_group": mg, "category": "gym", "equipment": eq,
            "instructions": instr, "tips": tips, "image_url": IMG[img_key], "youtube_id": yt}


# ═══════════════════════════════════════════════════════════════
# PECHO (Chest) — 30 nuevos ejercicios
# ═══════════════════════════════════════════════════════════════
PECHO_FULL = [
    _g("ch-press-banca-cerrado", "Press de Banca Cerrado", "Pecho", "Barra",
       ["Túmbate con agarre estrecho (manos hombros separadas).", "Saca la barra y baja al pecho.",
        "Codos pegados al cuerpo.", "Empuja arriba sin bloquear codos."],
       ["Trabaja pecho interno y tríceps", "No bajes ancho los codos"], "chest", "wxhiOFs6gKE"),
    _g("ch-press-spoto", "Press Spoto (pausa en pecho)", "Pecho", "Barra",
       ["Press de banca normal.", "Pausa la barra 1cm sobre el pecho 1-2 segundos.",
        "Sin tocar pecho.", "Empuja arriba."],
       ["Mejora fuerza en el punto débil", "Control absoluto"], "chest", "M59vAYz3nvQ"),
    _g("ch-press-pin", "Press con Pines (Pin Press)", "Pecho", "Barra",
       ["Pines en jaula a altura media-baja del pecho.", "Túmbate.", "Empuja desde reposo en los pines.",
        "Baja controlado a los pines de nuevo."],
       ["Sin acumular elasticidad", "Fuerza pura"], "chest", "EbAPAY-D0wQ"),
    _g("ch-press-mancuerna-inclinado", "Press Mancuernas Inclinado", "Pecho Superior", "Mancuernas",
       ["Banco a 30-45º.", "Mancuernas a la altura del pecho.", "Empuja arriba juntando ligeramente.",
        "Baja controlado."],
       ["Activa porción clavicular", "Sin chocar arriba"], "chest", "8iPEnn-ltC8"),
    _g("ch-press-mancuerna-declinado", "Press Mancuernas Declinado", "Pecho Inferior", "Mancuernas",
       ["Banco declinado, pies asegurados.", "Mancuernas en pecho.",
        "Empuja arriba.", "Baja controlado."],
       ["Trabaja pecho inferior", "Cuidado al sentarse"], "chest", "0G2_XV7slIg"),
    _g("ch-press-suelo", "Press de Suelo (Floor Press)", "Pecho", "Barra",
       ["Tumbado en el suelo, rodillas flexionadas.", "Agarra la barra ancho hombros.",
        "Baja hasta que codos toquen el suelo.", "Empuja arriba."],
       ["Reduce estrés del hombro", "Más enfasis tríceps"], "chest", "UdPkFnRrCsg"),
    _g("ch-press-arnold-pecho", "Press Inclinado Agarre Neutro", "Pecho", "Mancuernas",
       ["Banco inclinado.", "Mancuernas con palmas mirando entre sí.",
        "Empuja sin rotar.", "Baja controlado."],
       ["Más amable con hombros", "Activa pecho superior"], "chest", "8iPEnn-ltC8"),
    _g("ch-press-maquina-pecho", "Press en Máquina (Hammer Strength)", "Pecho", "Máquina",
       ["Sentado con espalda apoyada.", "Mangos a altura del pecho.",
        "Empuja al frente extendiendo brazos.", "Baja controlado."],
       ["Aislamiento sin estabilizadores", "Ideal para fallo muscular"], "chest", "TS80zzzAfaQ"),
    _g("ch-press-cable-cruzado", "Press de Pecho con Cables", "Pecho", "Polea",
       ["De pie entre dos poleas a altura media.", "Empuja al frente cruzando ligeramente.",
        "Aprieta el pecho.", "Vuelve controlado."],
       ["Tensión constante", "Cruza al final"], "chest", "Iwe6AmxVf7o"),
    _g("ch-cruces-polea-alta", "Cruces de Polea Alta", "Pecho Inferior", "Polea",
       ["Poleas en alto, agarra los mangos.", "Inclínate al frente.",
        "Cruza las manos abajo y al frente.", "Vuelve abriendo."],
       ["Pecho inferior", "Sin balanceo"], "chest", "taI4XduLpTk"),
    _g("ch-cruces-polea-baja", "Cruces de Polea Baja", "Pecho Superior", "Polea",
       ["Poleas en bajo.", "Sube las manos al frente y arriba en arco.",
        "Aprieta arriba.", "Vuelve abriendo."],
       ["Pecho superior", "Codos ligeramente flexionados"], "chest", "Iwe6AmxVf7o"),
    _g("ch-pec-deck", "Pec Deck (Contractor)", "Pecho", "Máquina",
       ["Sentado con espalda apoyada.", "Brazos en almohadillas o agarre.",
        "Junta los brazos al frente del pecho.", "Vuelve controlado."],
       ["Aislamiento puro", "Aprieta 1s arriba"], "chest", "Z5wGW9JtyOM"),
    _g("ch-pullover-barra", "Pullover con Barra", "Pecho/Dorsal", "Barra",
       ["Tumbado transversal en banco.", "Barra extendida sobre el pecho con codos ligeros.",
        "Baja por encima de la cabeza estirando.", "Vuelve a vertical."],
       ["Tronco arriba estable", "Estira pecho y dorsal"], "chest", "1gbeT3pp0iY"),
    _g("ch-pullover-polea", "Pullover en Polea", "Pecho/Dorsal", "Polea",
       ["De pie, polea alta con barra recta.", "Codos casi rectos.",
        "Tira hacia abajo y atrás de la cadera.", "Vuelve arriba lento."],
       ["Tensión constante", "Aísla el dorsal y pecho serrato"], "chest", "wcJ5vBNPCMo"),
    _g("ch-flexion-clasica", "Flexiones (Push-up)", "Pecho", "Peso corporal",
       ["Plancha alta con manos ancho hombros.", "Cuerpo recto en línea.",
        "Baja flexionando codos hasta casi tocar suelo.", "Empuja arriba."],
       ["Glúteo apretado", "Codos 45º del cuerpo"], "chest", "_l3ySVKYVJ8"),
    _g("ch-flexion-diamante", "Flexiones Diamante", "Tríceps/Pecho", "Peso corporal",
       ["Manos juntas formando diamante.", "Plancha alta.",
        "Baja al pecho.", "Empuja arriba."],
       ["Más tríceps que pecho", "Avanzado"], "triceps", "0SqmoEgWALY"),
    _g("ch-flexion-arquero", "Flexiones de Arquero", "Pecho", "Peso corporal",
       ["Plancha amplia.", "Baja hacia un lado flexionando solo ese codo.",
        "Vuelve y alterna."],
       ["Unilateral fuerte", "Avanzado"], "chest", "_l3ySVKYVJ8"),
    _g("ch-flexion-declinada", "Flexiones Declinadas", "Pecho Superior", "Banco",
       ["Pies elevados en banco.", "Manos en suelo plancha.",
        "Baja al suelo.", "Empuja arriba."],
       ["Pecho superior", "Mantén core firme"], "chest", "0pkjOk0EiAk"),
    _g("ch-flexion-deficit", "Flexiones con Déficit", "Pecho", "Mancuernas/Discos",
       ["Manos sobre discos elevadas 5-10cm.", "Plancha alta.",
        "Baja hasta más allá de la mano.", "Empuja arriba."],
       ["Más rango = más estímulo", "Útil cuando no tienes peso"], "chest", "_l3ySVKYVJ8"),
    _g("ch-flexion-explosiva", "Flexiones Explosivas", "Pecho", "Peso corporal",
       ["Plancha alta.", "Baja rápido.", "Empuja con fuerza despegando manos.",
        "Aterriza suave."],
       ["Pliometría", "Acabas con palmada para mayor reto"], "chest", "73qg9OXHvc8"),
    _g("ch-fondos-anillas", "Fondos en Anillas", "Pecho", "Anillas",
       ["Sujétate en las anillas.", "Inclínate al frente.",
        "Baja flexionando codos hasta el pecho.", "Empuja arriba."],
       ["Estabilidad extrema", "Avanzado"], "chest", "wjUmnZH528Y"),
    _g("ch-fondos-banco", "Fondos en Banco (Bench Dips)", "Tríceps", "Banco",
       ["Manos al borde del banco, espalda hacia él.", "Pies adelante.",
        "Baja flexionando codos.", "Empuja arriba."],
       ["Trabaja tríceps mayormente", "Codos hacia atrás"], "triceps", "tKjcgfu44sI"),
    _g("ch-svend-press", "Svend Press", "Pecho Interno", "Discos",
       ["De pie con un disco a la altura del pecho con ambas manos.", "Aprieta el disco.",
        "Empuja al frente.", "Vuelve."],
       ["Pecho interno extremo", "Aprieta isométricamente"], "chest", "GNL1sITBvO0"),
    _g("ch-pinch-press", "Pinch Press (mancuernas juntas)", "Pecho Interno", "Mancuernas",
       ["Tumbado, mancuernas juntas y palmas enfrentadas.", "Apriétalas todo el tiempo.",
        "Empuja arriba.", "Baja al pecho."],
       ["Pecho interior", "Sin separar mancuernas"], "chest", "BBe8frXh7H8"),
    _g("ch-jm-press-pecho", "Larsen Press", "Pecho", "Barra",
       ["Press banca con piernas extendidas hacia adelante (sin pies en el suelo).",
        "Baja al pecho.", "Empuja sin usar piernas."],
       ["Solo pecho/tríceps/hombro", "Difícil al inicio"], "chest", "WWdZUM_BkQE"),
    _g("ch-press-landmine", "Landmine Press a 1 brazo", "Pecho/Hombro", "Barra Landmine",
       ["De pie con barra anclada en esquina.", "Sujeta el extremo a un hombro.",
        "Empuja al frente y arriba.", "Baja controlado."],
       ["Pecho superior y hombro", "Ideal con hombros sensibles"], "chest", "OYjA1BCK2yI"),
    _g("ch-press-bottoms-up", "Press Bottoms-Up con Pesa Rusa", "Pecho/Estabilidad", "Kettlebell",
       ["Pesa rusa en posición invertida (asa abajo).", "Sujeta firme.",
        "Empuja arriba sin que se caiga.", "Baja con control."],
       ["Brutal para estabilidad", "Avanzado"], "chest", "YlrwvU3eEYQ"),
    _g("ch-flexion-spiderman", "Flexión Spider-Man", "Pecho/Core", "Peso corporal",
       ["Plancha alta.", "Baja flexión llevando rodilla al codo del mismo lado.",
        "Empuja y alterna lado."],
       ["Pecho + oblicuo", "Movimiento amplio"], "chest", "WI88aTu4kkk"),
    _g("ch-flexion-pseudo-planche", "Pseudo Planche Push-up", "Pecho/Hombro", "Peso corporal",
       ["Plancha con manos a la altura de la cadera.", "Inclínate al frente.",
        "Baja flexión.", "Empuja arriba."],
       ["Hombros y pecho superior", "Avanzado"], "chest", "_l3ySVKYVJ8"),
    _g("ch-bench-press-paws", "Press Banca Agarre Pausa", "Pecho", "Barra",
       ["Press banca con pausa de 3s en pecho.", "Empuja explosivo.",
        "Vuelve controlado."],
       ["Mejora la fuerza en el punto débil", "Sin elasticidad"], "chest", "M59vAYz3nvQ"),
]

# ═══════════════════════════════════════════════════════════════
# ESPALDA (Back) — 35 nuevos ejercicios
# ═══════════════════════════════════════════════════════════════
ESPALDA_FULL = [
    _g("bk-jalon-frontal", "Jalón al Pecho", "Dorsal", "Polea",
       ["Sentado con muslos asegurados.", "Agarre amplio prono en barra.",
        "Tira de la barra hacia el pecho superior.", "Vuelve arriba controlado."],
       ["Aprieta omoplatos", "No te recuestes en exceso"], "back", "iKrKgWR9wbY"),
    _g("bk-jalon-trasnuca", "Jalón Tras Nuca", "Dorsal", "Polea",
       ["Igual que jalón normal.", "Tira la barra detrás de la cabeza.",
        "Cuidado con el hombro."],
       ["Solo si tu movilidad lo permite", "Carga moderada"], "back", "iKrKgWR9wbY"),
    _g("bk-jalon-supino", "Jalón Agarre Supino", "Dorsal/Bíceps", "Polea",
       ["Agarre supino (palmas hacia ti).", "Tira al pecho.",
        "Aprieta dorsal y bíceps."],
       ["Más bíceps", "Codos cerca del cuerpo"], "back", "MgWbgwBzkJU"),
    _g("bk-jalon-cerrado", "Jalón Agarre Cerrado", "Dorsal", "Polea",
       ["Triángulo en la polea.", "Tira al esternón.",
        "Aprieta y vuelve."],
       ["Engrosa la espalda", "Codos pegados"], "back", "jUkAH-2BvdI"),
    _g("bk-jalon-1mano", "Jalón a 1 Brazo en Polea", "Dorsal", "Polea",
       ["De pie o de rodillas.", "Agarre alto con 1 mano.",
        "Tira hacia el costado.", "Vuelve."],
       ["Unilateral, máximo rango", "Aprieta dorsal"], "back", "qsqPrI4yZNg"),
    _g("bk-jalon-recto", "Pull-over en Polea Brazos Rectos", "Dorsal", "Polea",
       ["De pie, polea alta, barra.", "Brazos casi rectos.",
        "Tira hacia el muslo.", "Vuelve arriba lento."],
       ["Aísla dorsal sin bíceps", "Mantén la postura"], "back", "wcJ5vBNPCMo"),
    _g("bk-dominada-prona", "Dominada Prona", "Dorsal", "Barra",
       ["Cuélgate ancho prono.", "Tira hasta que la barbilla pase la barra.",
        "Baja controlado."],
       ["Rey ejercicios espalda", "Sin balanceo"], "back", "eGo4IYlbE5g"),
    _g("bk-dominada-supina", "Dominada Supina (Chin-up)", "Dorsal/Bíceps", "Barra",
       ["Agarre supino.", "Cuélgate.", "Tira hasta barbilla sobre barra.",
        "Baja controlado."],
       ["Más fácil", "Bíceps muy activado"], "back", "brhRXlOhsAM"),
    _g("bk-dominada-neutra", "Dominada Agarre Neutro", "Dorsal/Braquial", "Barra paralela",
       ["Agarre neutro entre paralelas.", "Sube hasta barbilla sobre la barra.",
        "Baja controlado."],
       ["Más amable con hombros", "Braquial activado"], "back", "PgKjsiCHGrU"),
    _g("bk-dominada-asistida", "Dominada Asistida", "Dorsal", "Máquina",
       ["Pisa en la plataforma de la máquina (peso compensa).", "Sube agarre prono.",
        "Baja controlado."],
       ["Para principiantes", "Reducir peso compensación gradualmente"], "back", "EbAPAY-D0wQ"),
    _g("bk-dominada-lastrada", "Dominada Lastrada", "Dorsal", "Cinturón con peso",
       ["Cinturón con disco.", "Cuélgate prono.",
        "Sube hasta barbilla.", "Baja controlado."],
       ["Sobrecarga progresiva", "Muy avanzado"], "back", "eGo4IYlbE5g"),
    _g("bk-pendlay-row", "Pendlay Row", "Dorsal", "Barra",
       ["Bisagra de cadera, torso casi paralelo al suelo.", "Barra apoyada en suelo cada rep.",
        "Tira al abdomen.", "Baja al suelo."],
       ["Muy explosivo", "Pausa abajo"], "back", "v34g7-mAhRk"),
    _g("bk-yates-row", "Yates Row", "Dorsal", "Barra",
       ["Inclinación 30º (más vertical que pendlay).", "Agarre supino.",
        "Tira al abdomen bajo.", "Baja controlado."],
       ["Bíceps muy activado", "Tira con codos atrás"], "back", "G8l_8chR5BE"),
    _g("bk-remo-mancuerna", "Remo con Mancuerna a 1 Mano", "Dorsal", "Mancuerna",
       ["1 rodilla y mano en banco.", "Mancuerna colgando.",
        "Tira al costado.", "Baja controlado."],
       ["Unilateral, gran rango", "Codo cerca del cuerpo"], "back", "roCP6wCXPqo"),
    _g("bk-remo-tbar", "T-Bar Row", "Dorsal", "T-Bar",
       ["De pie sobre la T-Bar.", "Inclínate al frente.", "Tira al pecho.",
        "Baja controlado."],
       ["Engrosa media espalda", "Pausa arriba"], "back", "j3Igk5nyZE4"),
    _g("bk-remo-maquina", "Remo en Máquina", "Dorsal", "Máquina",
       ["Sentado, pecho contra almohadilla.", "Tira de los mangos al abdomen.",
        "Aprieta omoplatos.", "Vuelve controlado."],
       ["Aislamiento", "Ideal al fallo"], "back", "tnpltY9TKsM"),
    _g("bk-remo-polea", "Remo Sentado en Polea", "Dorsal", "Polea",
       ["Sentado con triángulo o barra.", "Tira al ombligo.",
        "Aprieta omoplatos.", "Vuelve."],
       ["Pellizca la espalda", "Codos cerca del cuerpo"], "back", "GZbfZ033f74"),
    _g("bk-remo-cintura", "Remo a la Cintura con Cable", "Dorsal Bajo", "Polea",
       ["De pie con polea baja y agarre.", "Tira a la cintura.",
        "Vuelve."],
       ["Dorsal inferior", "Postura erguida"], "back", "GZbfZ033f74"),
    _g("bk-remo-cintura-banco", "Remo Apoyado en Banco Inclinado", "Dorsal", "Banco/Mancuernas",
       ["Pecho contra banco inclinado.", "Mancuernas colgando.",
        "Tira a los costados.", "Baja."],
       ["Sin trampa de espalda baja", "Aislamiento puro"], "back", "QkWeNCMbzKw"),
    _g("bk-remo-meadows", "Meadows Row (Landmine)", "Dorsal", "Landmine",
       ["Landmine, agarre supino con 1 mano.", "Postura lateral.",
        "Tira hacia la cadera.", "Baja."],
       ["Variante única", "Brutal para dorsal"], "back", "P9hcdsQYEZU"),
    _g("bk-deadlift-rumano", "Peso Muerto Rumano (RDL)", "Femoral/Espalda Baja", "Barra",
       ["De pie con barra a las caderas.", "Bisagra empujando glúteo atrás.",
        "Baja la barra a media tibia.", "Vuelve apretando glúteos."],
       ["Sin doblar la espalda", "Femoral muy activado"], "legs", "jEy_czb3RKA"),
    _g("bk-deadlift-convencional", "Peso Muerto Convencional", "Espalda/Pierna", "Barra",
       ["Barra en el suelo.", "Pies hombros, bisagra agarrando.",
        "Tira con piernas y caderas hasta extender.", "Baja controlado."],
       ["Rey de los ejercicios", "Espalda neutra"], "back", "ytGaGIn3SjE"),
    _g("bk-deadlift-sumo", "Peso Muerto Sumo", "Espalda/Pierna/Glúteo", "Barra",
       ["Pies bien anchos.", "Manos dentro de las piernas.",
        "Tira manteniendo pecho arriba.", "Baja."],
       ["Más glúteo y aductores", "Trabaja con caderas"], "legs", "wYREQkVtvEc"),
    _g("bk-deadlift-deficit", "Peso Muerto con Déficit", "Espalda/Pierna", "Barra",
       ["De pie sobre disco bajo.", "Peso muerto convencional.",
        "Mayor rango."],
       ["Más estímulo, más difícil", "Mucha movilidad"], "back", "ytGaGIn3SjE"),
    _g("bk-good-morning-barra", "Good Morning con Barra", "Espalda Baja/Femoral", "Barra",
       ["Barra alta en hombros.", "Bisagra al frente con piernas semi-rígidas.",
        "Vuelve apretando glúteos."],
       ["Cuidado lumbar", "Pesos moderados"], "legs", "vKPGe8zb2S0"),
    _g("bk-hyperextension", "Hiperextensión", "Espalda Baja/Glúteo", "Banco GHD",
       ["Apóyate en banco hyperextension.", "Baja el torso.",
        "Sube apretando glúteos a línea recta."],
       ["No te sobreextiendas", "Aprieta glúteos al final"], "back", "5_ovEW_J7VQ"),
    _g("bk-hyperextension-glute", "Hiperextensión con Énfasis Glúteo", "Glúteo", "Banco GHD",
       ["Pies abiertos hacia afuera.", "Sube redondeando ligeramente la espalda alta.",
        "Aprieta glúteos arriba."],
       ["Saca tensión de lumbares", "Glúteo dominante"], "glutes", "5_ovEW_J7VQ"),
    _g("bk-superman-barra", "Superman con Disco", "Lumbar", "Disco",
       ["Boca abajo, disco en pecho.", "Eleva pecho y piernas.",
        "Aguanta arriba 1s."],
       ["Lumbar dominante", "Sin forzar cuello"], "back", "z6PJMT2y8GQ"),
    _g("bk-shrug-barra", "Encogimientos con Barra", "Trapecio", "Barra",
       ["Barra al frente.", "Sube los hombros hacia las orejas.",
        "Aprieta arriba.", "Baja."],
       ["Sin rotar hombros", "Pausa arriba"], "back", "g6qbq4Lf1FI"),
    _g("bk-shrug-mancuerna", "Encogimientos con Mancuernas", "Trapecio", "Mancuernas",
       ["Mancuernas a los costados.", "Sube hombros.",
        "Aprieta y baja controlado."],
       ["Mayor rango", "Sin rotar"], "back", "cJRVVxmytaM"),
    _g("bk-shrug-trapecio-superior", "Trap Bar Shrug", "Trapecio", "Trap Bar",
       ["De pie en barra trap.", "Levanta encogiendo hombros.",
        "Aprieta arriba."],
       ["Postura más natural", "Pesos altos posibles"], "back", "g6qbq4Lf1FI"),
    _g("bk-face-pull-banda", "Face Pull con Banda", "Hombro Posterior/Trapecio", "Banda elástica",
       ["Anclada a altura de la cara.", "Tira a la cara abriendo brazos.",
        "Aprieta omoplatos."],
       ["Salud de hombros", "Útil en casa"], "shoulders", "rep-fERoeg8"),
    _g("bk-pull-up-australian", "Australian Pull-up (remo invertido)", "Espalda", "Barra baja",
       ["Tumbado bajo barra a altura cadera.", "Tira hasta tocar pecho.",
        "Baja controlado."],
       ["Variante de dominada para principiantes", "Cuerpo recto"], "back", "U6h_BPaW3qU"),
    _g("bk-rack-pull", "Rack Pull (peso muerto parcial)", "Espalda Alta/Trapecio", "Barra",
       ["Barra a altura rodilla en pines.", "Tira hasta extender cadera.",
        "Baja a los pines."],
       ["Sobrecarga la parte alta", "Pesos brutales"], "back", "ytGaGIn3SjE"),
    _g("bk-renegade-row", "Renegade Row", "Dorsal/Core", "Mancuernas",
       ["Plancha alta con mancuernas en las manos.", "Tira de una mancuerna al costado.",
        "Vuelve y alterna."],
       ["Espalda + core", "Sin rotar la cadera"], "back", "ITZsuv-PUg0"),
]

# ═══════════════════════════════════════════════════════════════
# HOMBROS (Shoulders) — 25 nuevos ejercicios
# ═══════════════════════════════════════════════════════════════
HOMBROS_FULL = [
    _g("sh-press-militar", "Press Militar de Pie", "Hombro", "Barra",
       ["De pie con barra a la altura del pecho.", "Aprieta core y glúteos.",
        "Empuja la barra arriba.", "Baja a la clavícula."],
       ["Cuidado lumbar", "Glúteo apretado"], "shoulders", "QAQ64hK4Xxs"),
    _g("sh-press-militar-sentado", "Press Militar Sentado con Barra", "Hombro", "Barra",
       ["Sentado en banco con respaldo.", "Barra al pecho superior.",
        "Empuja arriba.", "Baja a la clavícula."],
       ["Más estable", "Sin lumbar como en de pie"], "shoulders", "F3QY5vMz_6I"),
    _g("sh-press-mancuernas-sentado", "Press Mancuernas Sentado", "Hombro", "Mancuernas",
       ["Sentado, mancuernas a la altura del oído.", "Empuja arriba.",
        "Baja controlado."],
       ["Mayor rango que con barra", "Sin chocar arriba"], "shoulders", "qEwKCR5JCog"),
    _g("sh-press-mancuernas-pie", "Press Mancuernas de Pie", "Hombro", "Mancuernas",
       ["De pie, mancuernas a la altura del oído.", "Empuja arriba.",
        "Baja controlado."],
       ["Activa core", "Postura erguida"], "shoulders", "B-aVuyhvLHU"),
    _g("sh-arnold-press", "Arnold Press", "Hombro", "Mancuernas",
       ["Sentado, mancuernas frente a la cara con palmas hacia ti.",
        "Mientras subes, rota palmas hacia afuera.", "Termina con palmas al frente arriba.",
        "Baja invirtiendo el movimiento."],
       ["Trabaja todas las cabezas", "Movimiento amplio"], "shoulders", "6Z15_WdXmVw"),
    _g("sh-push-press", "Push Press", "Hombro", "Barra",
       ["Barra al pecho.", "Pequeño impulso de piernas.",
        "Empuja explosivo arriba.", "Baja controlado."],
       ["Permite más peso", "Útil para fuerza máxima"], "shoulders", "iaBVSJm78ko"),
    _g("sh-press-landmine", "Landmine Press 1 Brazo", "Hombro", "Landmine",
       ["Barra anclada en esquina.", "1 mano a la altura del hombro.",
        "Empuja al frente y arriba.", "Baja controlado."],
       ["Amable con hombros", "Patron natural"], "shoulders", "OYjA1BCK2yI"),
    _g("sh-press-maquina-hombro", "Press de Hombro en Máquina", "Hombro", "Máquina",
       ["Sentado en máquina.", "Mangos a altura de hombros.",
        "Empuja arriba.", "Baja controlado."],
       ["Aislamiento", "Ideal al fallo"], "shoulders", "qfNWLeo7yPk"),
    _g("sh-elevacion-lateral-mancuerna", "Elevación Lateral Mancuerna", "Hombro Medio", "Mancuernas",
       ["De pie con mancuernas a los costados.", "Sube los brazos a los lados hasta altura del hombro.",
        "Baja controlado."],
       ["Codos ligeramente flexionados", "Sin balancear"], "shoulders", "3VcKaXpzqRo"),
    _g("sh-elevacion-lateral-cable", "Elevación Lateral en Polea", "Hombro Medio", "Polea",
       ["Polea baja a un costado.", "Sube el brazo lateralmente.",
        "Baja controlado."],
       ["Tensión constante", "Aislamiento puro"], "shoulders", "0ku7ZZbJoDU"),
    _g("sh-elevacion-lateral-maquina", "Lateral Raise en Máquina", "Hombro Medio", "Máquina",
       ["Sentado, brazos en almohadillas.", "Sube los brazos a los lados.",
        "Baja controlado."],
       ["Ideal para principiantes", "Pesos altos posibles"], "shoulders", "PzsMitRdI_8"),
    _g("sh-elevacion-frontal-disco", "Elevación Frontal con Disco", "Hombro Frontal", "Disco",
       ["Disco con dos manos al frente.", "Sube hasta altura de la cara.",
        "Baja controlado."],
       ["Hombro anterior", "Sin balanceo"], "shoulders", "tj0NAa4kFco"),
    _g("sh-elevacion-frontal-mancuerna", "Elevación Frontal Mancuernas", "Hombro Frontal", "Mancuernas",
       ["Mancuernas frente a los muslos.", "Sube alternando hasta hombros.",
        "Baja controlado."],
       ["Hombro anterior", "Pequeñas pausas"], "shoulders", "h8B5GEwj5Cw"),
    _g("sh-elevacion-frontal-polea", "Elevación Frontal en Polea", "Hombro Frontal", "Polea",
       ["Polea baja con barra.", "Sube hasta hombros.",
        "Baja controlado."],
       ["Tensión constante", "Sin balancear"], "shoulders", "h8B5GEwj5Cw"),
    _g("sh-pajaro-mancuerna", "Pájaros (Reverse Fly) Mancuerna", "Hombro Posterior", "Mancuernas",
       ["Inclinado al frente con mancuernas colgando.", "Abre brazos a los lados.",
        "Aprieta atrás.", "Baja."],
       ["Hombro posterior", "Codos ligeramente flexionados"], "shoulders", "lP-FjzkTKR0"),
    _g("sh-pajaro-maquina", "Reverse Pec Deck", "Hombro Posterior", "Máquina",
       ["Sentado mirando la máquina.", "Tira los brazos hacia atrás.",
        "Aprieta y vuelve."],
       ["Aísla deltoide posterior", "Ideal al fallo"], "shoulders", "yYrDSz67-IQ"),
    _g("sh-face-pull-cuerda", "Face Pull con Cuerda", "Hombro Posterior/Trapecio", "Polea",
       ["Polea alta con cuerda.", "Tira a la cara separando manos.",
        "Aprieta omoplatos."],
       ["Salud de hombros imprescindible", "Pesos moderados"], "shoulders", "rep-fERoeg8"),
    _g("sh-remo-erguido", "Remo al Mentón", "Hombro/Trapecio", "Barra",
       ["Barra delante de los muslos, agarre estrecho.", "Tira la barra hacia el mentón.",
        "Codos altos.", "Baja."],
       ["Cuidado movilidad hombro", "Codos no más altos que hombros"], "shoulders", "x9eVnkP8Cms"),
    _g("sh-cuban-press", "Cuban Press", "Manguito Rotador/Hombro", "Mancuernas/Barra",
       ["Remo al mentón con codos altos.", "Rota brazos arriba.",
        "Press arriba.", "Vuelve invirtiendo."],
       ["Salud del manguito", "Pesos ligeros"], "shoulders", "8VtULmzAmzU"),
    _g("sh-y-raise", "Y-Raise", "Trapecio Inferior", "Mancuernas",
       ["Boca abajo en banco inclinado.", "Sube los brazos en forma de Y.",
        "Baja controlado."],
       ["Postura, salud espalda alta", "Pesos ligeros"], "shoulders", "5DI04YOgfrU"),
    _g("sh-handstand-pushup", "Handstand Push-up", "Hombro", "Pared",
       ["Pino contra pared.", "Baja la cabeza al suelo.",
        "Empuja arriba."],
       ["Avanzadísimo", "Practica el pino antes"], "shoulders", "sk2LCB6yJ-c"),
    _g("sh-press-pike", "Pike Push-up", "Hombro", "Peso corporal",
       ["Plancha con cadera arriba (V invertida).", "Baja la cabeza al suelo.",
        "Empuja arriba."],
       ["Progresión a HSPU", "Hombro dominante"], "shoulders", "x7gYvXyvCwE"),
    _g("sh-press-z", "Z Press", "Hombro/Core", "Barra/Mancuernas",
       ["Sentado en suelo con piernas extendidas.", "Press de hombros.",
        "Empuja arriba sin recostarte.", "Baja."],
       ["Brutal para core y hombros", "Pesos moderados"], "shoulders", "U2vRPEWrOLU"),
    _g("sh-bradford-press", "Bradford Press", "Hombro", "Barra",
       ["Press desde el frente al detrás de la cabeza.", "Sin bloquear arriba.",
        "Movimiento continuo."],
       ["Tensión constante", "Movilidad necesaria"], "shoulders", "QAQ64hK4Xxs"),
    _g("sh-shoulder-tap", "Shoulder Tap", "Hombro/Core", "Peso corporal",
       ["Plancha alta.", "Toca el hombro contrario con la mano alternando.",
        "Cadera estable."],
       ["Estabilidad total", "Sin rotar caderas"], "shoulders", "ASdvN_XEl_c"),
]

# ═══════════════════════════════════════════════════════════════
# BÍCEPS — 22 nuevos ejercicios
# ═══════════════════════════════════════════════════════════════
BICEPS_FULL = [
    _g("bi-curl-barra-z", "Curl con Barra Z", "Bíceps", "Barra Z",
       ["De pie con barra Z.", "Codos pegados al cuerpo.",
        "Sube hasta máxima contracción.", "Baja controlado."],
       ["Más amable con muñecas", "Sin balancear"], "biceps", "EZS8hKHIxhI"),
    _g("bi-curl-barra-recta", "Curl con Barra Recta", "Bíceps", "Barra",
       ["De pie con barra recta.", "Sube manteniendo codos fijos.",
        "Baja controlado."],
       ["Pico bíceps", "Sin balanceo de espalda"], "biceps", "kwG2ipFRgfo"),
    _g("bi-curl-mancuerna-alterno", "Curl Alterno con Mancuerna", "Bíceps", "Mancuernas",
       ["Mancuernas a los lados.", "Sube alternando con supinación.",
        "Baja controlado."],
       ["Cada brazo trabaja", "Aprieta arriba"], "biceps", "ykJmrZ5v0Oo"),
    _g("bi-curl-mancuerna-simultaneo", "Curl Simultáneo Mancuernas", "Bíceps", "Mancuernas",
       ["Mancuernas a los lados.", "Sube ambas a la vez.",
        "Baja controlado."],
       ["Más simple", "Pesos algo menores"], "biceps", "ykJmrZ5v0Oo"),
    _g("bi-curl-martillo-pie", "Curl Martillo de Pie", "Braquial/Bíceps", "Mancuernas",
       ["Agarre neutro.", "Sube como martillo.", "Baja controlado."],
       ["Braquial dominante", "Engruesa el brazo"], "biceps", "zC3nLlEvin4"),
    _g("bi-curl-martillo-cuerda", "Curl Martillo en Polea con Cuerda", "Braquial/Bíceps", "Polea",
       ["Polea baja con cuerda.", "Curl martillo manteniendo agarre neutro.",
        "Baja controlado."],
       ["Tensión constante", "Más rango que mancuernas"], "biceps", "tj-cZAYEpfA"),
    _g("bi-curl-zottman", "Curl Zottman", "Bíceps/Antebrazo", "Mancuernas",
       ["Sube como curl normal.", "Rota a posición prono arriba.",
        "Baja como reverse curl.", "Rota al final."],
       ["Bíceps + antebrazo", "Movimiento único"], "biceps", "ZrpRBgswtHs"),
    _g("bi-curl-predicador", "Curl en Banco Scott (Predicador)", "Bíceps", "Banco Scott",
       ["Brazos apoyados en banco scott.", "Curl con barra Z o mancuerna.",
        "Sube y baja controlado."],
       ["Aísla porción larga", "Sin tirones"], "biceps", "fIWP-FRFNU0"),
    _g("bi-curl-spider", "Curl Spider", "Bíceps", "Banco inclinado",
       ["Boca abajo en banco inclinado.", "Mancuernas colgando.",
        "Curl arriba.", "Baja controlado."],
       ["Aísla bíceps puro", "Pico de contracción"], "biceps", "UpxsPV2Jpz0"),
    _g("bi-curl-inclinado", "Curl Inclinado en Banco", "Bíceps Largo", "Banco/Mancuernas",
       ["Banco a 60º.", "Mancuernas colgando.",
        "Curl con supinación.", "Baja completo abajo."],
       ["Estira bíceps largo", "Brazos detrás del cuerpo"], "biceps", "soxrZlIl35U"),
    _g("bi-curl-concentrado", "Curl Concentrado", "Bíceps", "Mancuerna",
       ["Sentado con codo apoyado en muslo.", "Curl hasta el hombro.",
        "Baja controlado."],
       ["Pico extremo", "Aísla 100%"], "biceps", "0AUGkch3tGc"),
    _g("bi-curl-cable-1mano", "Curl en Polea 1 Brazo", "Bíceps", "Polea",
       ["Polea baja a 1 lado.", "Curl con 1 mano.",
        "Vuelve."],
       ["Tensión constante", "Unilateral"], "biceps", "85ZQzFVwtsk"),
    _g("bi-curl-cable-barra", "Curl con Barra en Polea", "Bíceps", "Polea",
       ["Polea baja con barra.", "Curl manteniendo codos fijos.",
        "Baja controlado."],
       ["Tensión 100%", "Pico claro"], "biceps", "tj-cZAYEpfA"),
    _g("bi-curl-cable-cuerda", "Curl Cuerda Bayesian (lateral)", "Bíceps Largo", "Polea",
       ["Polea baja, mango con 1 mano detrás del cuerpo.",
        "Curl manteniendo codo atrás.", "Vuelve."],
       ["Estira la porción larga", "Posición única"], "biceps", "85ZQzFVwtsk"),
    _g("bi-curl-21s", "21s con Barra", "Bíceps", "Barra Z",
       ["7 reps mitad inferior + 7 reps mitad superior + 7 reps completas.",
        "Sin descanso.", "Quema brutal."],
       ["Técnica intensiva", "Pesos moderados"], "biceps", "WRFL6FY3xks"),
    _g("bi-curl-arrastre", "Drag Curl", "Bíceps", "Barra",
       ["De pie con barra.", "Sube arrastrando barra cerca del cuerpo.",
        "Codos van atrás.", "Baja."],
       ["Aísla bíceps puro", "Sin tirar al frente"], "biceps", "G-7CnQX6BPg"),
    _g("bi-curl-reverse", "Reverse Curl (agarre prono)", "Antebrazo/Braquial", "Barra/Z",
       ["Agarre prono (palmas abajo).", "Sube manteniendo codos.",
        "Baja controlado."],
       ["Antebrazo dominante", "Pesos menores"], "biceps", "_0_TPN1U21M"),
    _g("bi-curl-pinch", "Pinch Curl con Disco", "Antebrazo/Bíceps", "Discos",
       ["Sujeta 2 discos juntos por los bordes.", "Curl manteniendo agarre.",
        "Vuelve."],
       ["Agarre + bíceps", "Avanzado"], "biceps", "_0_TPN1U21M"),
    _g("bi-curl-pesa-rusa", "Curl con Pesa Rusa", "Bíceps", "Kettlebell",
       ["Pesa rusa en mano.", "Curl con peso descentrado.",
        "Vuelve."],
       ["Estabilidad extra", "Variante interesante"], "biceps", "ykJmrZ5v0Oo"),
    _g("bi-chin-up-negativa", "Chin-up Negativo", "Bíceps/Dorsal", "Barra",
       ["Sube con ayuda hasta arriba.", "Baja MUY lento (5-8 segundos).",
        "Repite."],
       ["Para conseguir 1ª dominada", "Excéntrico mata"], "biceps", "brhRXlOhsAM"),
    _g("bi-curl-incline-cable", "Curl Inclinado en Polea", "Bíceps", "Polea/Banco",
       ["Banco inclinado entre poleas bajas.", "Curl con tensión constante.",
        "Vuelve."],
       ["Estira y contrae al máximo", "Setup avanzado"], "biceps", "soxrZlIl35U"),
    _g("bi-curl-tate", "Tate Curl", "Bíceps", "Mancuernas",
       ["Tumbado en banco con mancuernas.", "Curl flexionando codos hacia los hombros.",
        "Baja."],
       ["Variante única", "Aprieta arriba"], "biceps", "0AUGkch3tGc"),
]

# ═══════════════════════════════════════════════════════════════
# TRÍCEPS — 22 nuevos ejercicios
# ═══════════════════════════════════════════════════════════════
TRICEPS_FULL = [
    _g("tr-press-frances", "Press Francés (Skull Crusher)", "Tríceps", "Barra Z",
       ["Tumbado con barra Z.", "Brazos verticales.",
        "Baja la barra a la frente.", "Extiende arriba."],
       ["Codos fijos", "Cuidado con la cabeza"], "triceps", "d_KZxkY_0cM"),
    _g("tr-press-frances-mancuerna", "Skull Crusher con Mancuernas", "Tríceps", "Mancuernas",
       ["Tumbado con mancuernas.", "Baja a las orejas.",
        "Extiende arriba."],
       ["Mayor rango", "Codos siempre fijos"], "triceps", "Bk6L7FZqLBI"),
    _g("tr-press-cerrado", "Press Banca Agarre Cerrado", "Tríceps/Pecho", "Barra",
       ["Press banca con manos a hombros.", "Codos pegados al cuerpo.",
        "Baja al pecho.", "Empuja arriba."],
       ["Tríceps dominante", "Más fuerza posible"], "triceps", "wxhiOFs6gKE"),
    _g("tr-jm-press", "JM Press", "Tríceps", "Barra",
       ["Mezcla de press francés y press banca.",
        "Baja barra hacia el cuello.", "Empuja arriba."],
       ["Avanzado", "Pesos altos posibles"], "triceps", "RTZIZQQ5wO0"),
    _g("tr-extension-overhead-mancuerna", "Extensión Overhead 1 Mancuerna", "Tríceps Largo", "Mancuerna",
       ["Mancuerna con ambas manos detrás de la cabeza.", "Extiende brazos arriba.",
        "Baja controlado."],
       ["Estira porción larga", "Codos cerca de la cabeza"], "triceps", "_gsUck-7M74"),
    _g("tr-extension-overhead-cuerda", "Extensión Overhead Polea con Cuerda", "Tríceps Largo", "Polea",
       ["De rodillas o de pie de espaldas a polea alta.", "Cuerda detrás de la cabeza.",
        "Extiende al frente.", "Vuelve."],
       ["Tensión constante", "Estiramiento brutal"], "triceps", "X3MeBp3qrNY"),
    _g("tr-extension-trasnuca-barra", "Extensión Tras Nuca con Barra", "Tríceps", "Barra Z",
       ["Sentado con barra Z arriba.", "Baja detrás de la cabeza.",
        "Extiende arriba."],
       ["Activa porción larga", "Pesos moderados"], "triceps", "_gsUck-7M74"),
    _g("tr-pushdown-cuerda", "Push-down con Cuerda", "Tríceps", "Polea",
       ["Polea alta con cuerda.", "Codos pegados al cuerpo.",
        "Empuja abajo abriendo cuerda al final.", "Vuelve."],
       ["Aprieta abajo", "Codos fijos"], "triceps", "vB5OHsJ3EME"),
    _g("tr-pushdown-barra", "Push-down con Barra Recta", "Tríceps", "Polea",
       ["Polea alta con barra recta.", "Codos pegados.",
        "Empuja abajo.", "Vuelve."],
       ["Pesos altos posibles", "Sin mover codos"], "triceps", "2-LAMcpzODU"),
    _g("tr-pushdown-z", "Push-down con Barra Z", "Tríceps", "Polea",
       ["Igual que push-down pero con barra Z.",
        "Más amable con muñecas."],
       ["Si las muñecas se quejan", "Variante práctica"], "triceps", "2-LAMcpzODU"),
    _g("tr-pushdown-supino", "Push-down Agarre Supino", "Tríceps Medial", "Polea",
       ["Polea alta, agarre supino con barra recta.",
        "Empuja abajo.", "Vuelve."],
       ["Activa cabeza medial", "Variante diferente"], "triceps", "vB5OHsJ3EME"),
    _g("tr-kickback", "Patada de Tríceps (Kickback)", "Tríceps", "Mancuerna",
       ["Inclinado al frente con mancuerna.", "Brazo a 90º.",
        "Extiende atrás.", "Vuelve."],
       ["Aislamiento", "Codo fijo"], "triceps", "ZIuVpvogi9c"),
    _g("tr-kickback-cable", "Kickback en Polea", "Tríceps", "Polea",
       ["Polea alta a un lado.", "Inclinado.",
        "Extiende atrás manteniendo codo fijo.", "Vuelve."],
       ["Tensión constante", "Aprieta atrás"], "triceps", "ZIuVpvogi9c"),
    _g("tr-fondos-banco-tri", "Fondos en Banco para Tríceps", "Tríceps", "Banco",
       ["Manos en banco tras de ti.", "Pies adelantados.",
        "Baja flexionando codos.", "Empuja arriba."],
       ["Codos atrás", "Sin abrir"], "triceps", "tKjcgfu44sI"),
    _g("tr-fondos-paralelas", "Fondos Verticales para Tríceps", "Tríceps", "Paralelas",
       ["Sujétate en paralelas con torso vertical.", "Baja flexionando codos.",
        "Empuja arriba."],
       ["Más vertical = más tríceps", "Codos rectos atrás"], "triceps", "wjUmnZH528Y"),
    _g("tr-diamond-pushup", "Flexiones Diamante", "Tríceps", "Peso corporal",
       ["Manos juntas formando diamante.", "Plancha alta.",
        "Baja al pecho.", "Empuja arriba."],
       ["Tríceps dominante", "Avanzado"], "triceps", "0SqmoEgWALY"),
    _g("tr-extension-1mano-cable", "Extensión 1 Mano en Polea", "Tríceps", "Polea",
       ["Polea alta con 1 mango.", "Brazo en 90º.",
        "Extiende abajo.", "Vuelve."],
       ["Unilateral", "Tensión constante"], "triceps", "vB5OHsJ3EME"),
    _g("tr-tricep-press-maquina", "Press de Tríceps en Máquina", "Tríceps", "Máquina",
       ["Sentado en máquina específica.", "Empuja los mangos abajo o al frente.",
        "Vuelve."],
       ["Aislamiento puro", "Ideal al fallo"], "triceps", "iPI6qkv-vBU"),
    _g("tr-skull-crusher-cable", "Skull Crusher en Polea", "Tríceps", "Polea",
       ["Polea baja con cuerda detrás de la cabeza.", "Tumbado en banco.",
        "Extiende al techo.", "Baja a la frente."],
       ["Tensión 100%", "Variante avanzada"], "triceps", "d_KZxkY_0cM"),
    _g("tr-tate-press", "Tate Press", "Tríceps", "Mancuernas",
       ["Tumbado con mancuernas arriba.", "Codos al frente.",
        "Baja mancuernas hacia el pecho cruzando.", "Extiende arriba."],
       ["Variante única", "Pesos moderados"], "triceps", "Bk6L7FZqLBI"),
    _g("tr-pushup-decline", "Flexiones Declinadas Cerradas", "Tríceps", "Banco",
       ["Pies elevados.", "Manos cerradas.",
        "Baja flexionando codos.", "Empuja arriba."],
       ["Tríceps dominante", "Avanzado"], "triceps", "0SqmoEgWALY"),
    _g("tr-press-frances-suelo", "Press Francés Suelo", "Tríceps", "Mancuernas",
       ["Tumbado en suelo con mancuernas.", "Codos descansan en el suelo.",
        "Extiende arriba.", "Baja."],
       ["Útil sin banco", "Limita rango"], "triceps", "Bk6L7FZqLBI"),
]

# ═══════════════════════════════════════════════════════════════
# ANTEBRAZO — 12 ejercicios
# ═══════════════════════════════════════════════════════════════
ANTEBRAZO_FULL = [
    _g("fa-wrist-curl", "Wrist Curl (Flexión Muñeca)", "Antebrazo Flexor", "Mancuernas",
       ["Sentado con antebrazos en muslos.", "Palmas hacia arriba.",
        "Sube las muñecas.", "Baja completo."],
       ["Pesos ligeros", "Aislamiento"], "biceps", "kkVMOGfkmpE"),
    _g("fa-reverse-wrist-curl", "Reverse Wrist Curl", "Antebrazo Extensor", "Mancuernas",
       ["Antebrazos en muslos, palmas abajo.", "Sube muñecas.", "Baja."],
       ["Equilibra los flexores", "Pesos muy ligeros"], "biceps", "kkVMOGfkmpE"),
    _g("fa-finger-curl", "Finger Curl", "Antebrazo", "Barra/Mancuerna",
       ["Sentado, antebrazos en muslos.", "Deja que la barra ruede a los dedos.",
        "Cierra el agarre.", "Sube."],
       ["Trabaja el agarre", "Pesos moderados"], "biceps", "kkVMOGfkmpE"),
    _g("fa-farmer-walk", "Farmer's Walk", "Antebrazo/Trapecio/Core", "Mancuernas/Pesa",
       ["Carga 2 mancuernas pesadas a los lados.", "Camina recto 30-50 metros.",
        "Postura erguida."],
       ["Brutal para agarre", "Activa todo el cuerpo"], "fullbody", "Fkzk_RqlYig"),
    _g("fa-plate-pinch", "Plate Pinch", "Antebrazo/Agarre", "Discos",
       ["Sujeta 2 discos lisos juntos por los bordes.", "Aguanta 20-30 segundos.",
        "Suelta y descansa."],
       ["Pinza brutal", "Agarre puro"], "biceps", "lJiZJ2-Pl-c"),
    _g("fa-dead-hang", "Dead Hang", "Antebrazo/Hombro", "Barra",
       ["Cuélgate de barra con brazos extendidos.", "Aguanta 30s-2min.",
        "Hombros activos hacia abajo."],
       ["Trabaja agarre", "Salud de hombros"], "back", "rUaUvabsnjs"),
    _g("fa-zottman-curl", "Zottman Curl", "Bíceps/Antebrazo", "Mancuernas",
       ["Curl supino arriba.", "Rota a prono.", "Baja prono.",
        "Rota a supino abajo."],
       ["Bíceps + antebrazo", "Movimiento único"], "biceps", "ZrpRBgswtHs"),
    _g("fa-reverse-curl", "Reverse Curl con Barra", "Antebrazo/Braquial", "Barra Z",
       ["De pie con barra Z, agarre prono.", "Curl con palmas abajo.",
        "Baja controlado."],
       ["Antebrazo extensor + braquial", "Pesos ligeros"], "biceps", "_0_TPN1U21M"),
    _g("fa-hammer-curl-cuerda", "Hammer Curl en Polea", "Antebrazo/Braquial", "Polea",
       ["Polea baja con cuerda.", "Curl martillo.",
        "Baja controlado."],
       ["Tensión constante", "Engruesa antebrazo"], "biceps", "tj-cZAYEpfA"),
    _g("fa-towel-pullup", "Dominada con Toalla", "Antebrazo/Espalda", "Barra/Toalla",
       ["Pasa toalla por barra.", "Sujeta los extremos.",
        "Dominada agarrando la toalla.", "Baja."],
       ["Agarre extremo", "Avanzadísimo"], "back", "eGo4IYlbE5g"),
    _g("fa-grip-trainer", "Hand Gripper", "Antebrazo", "Hand gripper",
       ["Aprieta el grip al máximo.", "Aguanta 2-3 segundos.",
        "Suelta despacio."],
       ["En cualquier sitio", "Resistencias diferentes"], "biceps", "kkVMOGfkmpE"),
    _g("fa-towel-row", "Remo con Toalla", "Antebrazo/Espalda", "Barra/Toalla",
       ["Toalla por barra TRX.", "Remo invertido sujetando toalla.",
        "Tira al pecho."],
       ["Variante divertida", "Trabaja agarre"], "back", "U6h_BPaW3qU"),
]

# ═══════════════════════════════════════════════════════════════
# PIERNAS — 40 nuevos ejercicios (cuádriceps, femoral, gemelos, glúteos)
# ═══════════════════════════════════════════════════════════════
PIERNAS_FULL = [
    _g("le-sentadilla-libre", "Sentadilla Libre con Barra", "Cuádriceps/Glúteo", "Barra",
       ["Barra en hombros (alta o baja).", "Pies hombros, ligera apertura.",
        "Baja hasta paralelo o más.", "Sube empujando con piernas."],
       ["Rey de los ejercicios pierna", "Espalda neutra"], "legs", "ultWZbUMPL8"),
    _g("le-sentadilla-frontal", "Sentadilla Frontal (Front Squat)", "Cuádriceps", "Barra",
       ["Barra en deltoides anterior.", "Codos altos.",
        "Baja hasta paralelo.", "Sube."],
       ["Cuádriceps dominante", "Más amable con espalda"], "legs", "tlfahNdNPPI"),
    _g("le-sentadilla-zercher", "Sentadilla Zercher", "Cuádriceps/Core", "Barra",
       ["Barra en pliegue de los codos.", "Sentadilla profunda.",
        "Sube apretando core."],
       ["Brutal para core", "Activa toda la pierna"], "legs", "wWIVN-2WBmU"),
    _g("le-sentadilla-overhead", "Overhead Squat", "Cuádriceps/Core/Hombro", "Barra",
       ["Barra extendida sobre cabeza.", "Sentadilla profunda.",
        "Sube manteniendo barra arriba."],
       ["Movilidad total cuerpo", "Pesos ligeros"], "legs", "Tjgz_AjMYS4"),
    _g("le-sentadilla-pause", "Sentadilla con Pausa", "Cuádriceps", "Barra",
       ["Sentadilla normal.", "Pausa 2-3 segundos abajo.",
        "Sube explosivo."],
       ["Mejora explosividad", "Sin elasticidad"], "legs", "ultWZbUMPL8"),
    _g("le-sentadilla-tempo", "Sentadilla Tempo (3-1-1)", "Cuádriceps", "Barra",
       ["3s para bajar, 1s pausa, 1s para subir.",
        "Control total.", "Aumenta tiempo bajo tensión."],
       ["Hipertrofia avanzada", "Pesos moderados"], "legs", "ultWZbUMPL8"),
    _g("le-sentadilla-goblet", "Sentadilla Goblet", "Cuádriceps", "Mancuerna/Pesa",
       ["Mancuerna o pesa rusa al pecho.", "Sentadilla profunda.",
        "Sube."],
       ["Aprende patrón de sentadilla", "Núcleo activado"], "legs", "MeIiIdhvXT4"),
    _g("le-sentadilla-bulgara-mancuerna", "Sentadilla Búlgara con Mancuernas", "Cuádriceps/Glúteo", "Mancuernas",
       ["Pie trasero en banco.", "Mancuernas a los lados.",
        "Baja flexionando rodilla delantera.", "Sube."],
       ["Unilateral brutal", "Glúteo + cuádriceps"], "legs", "2C-uNgKwPLE"),
    _g("le-sentadilla-bulgara-barra", "Sentadilla Búlgara con Barra", "Cuádriceps/Glúteo", "Barra",
       ["Barra en hombros.", "Pie trasero en banco.",
        "Baja sentadilla 1 pierna.", "Sube."],
       ["Más peso", "Avanzado"], "legs", "2C-uNgKwPLE"),
    _g("le-pistol-squat", "Pistol Squat", "Cuádriceps/Glúteo/Equilibrio", "Peso corporal",
       ["1 pierna extendida al frente.", "Baja en sentadilla con la otra.",
        "Sube empujando."],
       ["Avanzadísimo", "Movilidad necesaria"], "legs", "wKTRy-FLFRY"),
    _g("le-prensa", "Prensa de Piernas", "Cuádriceps/Glúteo", "Máquina",
       ["Sentado en máquina prensa.", "Pies hombros.",
        "Baja flexionando rodillas.", "Empuja arriba."],
       ["Pesos altos seguros", "Cuidado bloqueo rodillas"], "legs", "IZxyjW7MPJQ"),
    _g("le-prensa-1pierna", "Prensa a 1 Pierna", "Cuádriceps/Glúteo", "Máquina",
       ["Igual que prensa pero con 1 pierna.", "Otra pierna fuera de plataforma."],
       ["Unilateral", "Equilibra desbalances"], "legs", "IZxyjW7MPJQ"),
    _g("le-hack-squat", "Hack Squat", "Cuádriceps", "Máquina",
       ["En máquina hack squat.", "Espalda apoyada.",
        "Baja flexionando rodillas.", "Sube."],
       ["Cuádriceps dominante", "Espalda protegida"], "legs", "0tn5K9NlCfo"),
    _g("le-leg-extension", "Extensión de Cuádriceps", "Cuádriceps", "Máquina",
       ["Sentado en máquina.", "Almohadilla en tobillos.",
        "Extiende rodillas.", "Baja controlado."],
       ["Aislamiento puro", "Aprieta arriba"], "legs", "GuIrxR1Ye-w"),
    _g("le-leg-curl-tumbado", "Curl Femoral Tumbado", "Femoral", "Máquina",
       ["Tumbado en máquina.", "Almohadilla en tobillos.",
        "Flexiona rodillas hacia glúteos.", "Baja controlado."],
       ["Femoral aislado", "Cadera abajo"], "legs", "1Tq3QdYUuHs"),
    _g("le-leg-curl-sentado", "Curl Femoral Sentado", "Femoral", "Máquina",
       ["Sentado en máquina específica.", "Flexiona rodillas.",
        "Vuelve."],
       ["Mayor activación femoral", "Pesos altos posibles"], "legs", "ELOCsoDSmrg"),
    _g("le-leg-curl-pelota", "Curl Femoral con Pelota", "Femoral", "Pelota suiza",
       ["Tumbado, talones en pelota.", "Eleva caderas.",
        "Acerca pelota al glúteo flexionando rodillas.", "Estira."],
       ["Femoral + glúteo", "Sin máquina"], "legs", "Bjvw_J6kCHE"),
    _g("le-stiff-leg-deadlift", "Peso Muerto Piernas Rígidas", "Femoral", "Barra",
       ["De pie con barra.", "Bisagra con piernas casi rígidas.",
        "Baja la barra a media tibia.", "Sube apretando glúteos."],
       ["Femoral brutal", "Sin doblar espalda"], "legs", "jEy_czb3RKA"),
    _g("le-good-morning-pierna", "Good Morning con Barra", "Femoral/Lumbar", "Barra",
       ["Barra alta en hombros.", "Bisagra al frente piernas semi-rígidas.",
        "Vuelve."],
       ["Cuidado lumbar", "Pesos moderados"], "legs", "vKPGe8zb2S0"),
    _g("le-zancada-andando", "Zancadas Andando", "Pierna/Glúteo", "Mancuernas",
       ["Mancuernas a los lados.", "Da paso largo y baja rodilla trasera.",
        "Avanza alternando."],
       ["Funcional", "Equilibrio + fuerza"], "legs", "L8fvypPrzzs"),
    _g("le-zancada-inversa", "Zancadas Inversas", "Cuádriceps/Glúteo", "Mancuernas",
       ["Mancuernas a los lados.", "Da paso atrás flexionando.",
        "Vuelve y alterna."],
       ["Más amable con rodillas", "Glúteo activado"], "legs", "L8fvypPrzzs"),
    _g("le-zancada-lateral", "Zancada Lateral", "Aductores/Cuádriceps", "Mancuernas",
       ["Mancuernas a los lados.", "Paso lateral flexionando una rodilla.",
        "Vuelve y alterna."],
       ["Aductores trabajados", "Movilidad de cadera"], "legs", "QRKNgwWbm5M"),
    _g("le-step-up", "Step-up", "Glúteo/Cuádriceps", "Banco/Mancuernas",
       ["Mancuernas a los lados.", "Sube a banco con 1 pierna.",
        "Baja controlado.", "Alterna."],
       ["Funcional", "Equilibrio"], "legs", "WCFCdxzFBa4"),
    _g("le-step-up-alto", "Step-up Alto", "Glúteo/Cuádriceps", "Cajón alto",
       ["Cajón alto (rodilla 90º).", "Sube empujando con la pierna.",
        "Baja controlado."],
       ["Más glúteo", "Pesos según nivel"], "legs", "WCFCdxzFBa4"),
    _g("le-sissy-squat", "Sissy Squat", "Cuádriceps", "Peso corporal",
       ["De pie sujétate de algo.", "Inclínate hacia atrás flexionando rodillas.",
        "Casi tocas el suelo con rodillas.", "Sube."],
       ["Aísla cuádriceps", "Cuidado rodillas"], "legs", "VnNEh4XmJDg"),
    _g("le-cossack-squat", "Sentadilla Cossack", "Aductores/Cuádriceps", "Peso corporal",
       ["Pies muy separados.", "Baja a un lado flexionando 1 rodilla.",
        "Otro pie extendido.", "Alterna."],
       ["Movilidad lateral", "Aductores"], "legs", "8Wu_sWUWvWc"),
    _g("le-jefferson-squat", "Jefferson Squat", "Cuádriceps/Glúteo", "Barra",
       ["Barra entre piernas, pies separados.", "Sentadilla con barra.",
        "Sube."],
       ["Variante única", "Postura asimétrica"], "legs", "ultWZbUMPL8"),
    _g("le-belt-squat", "Belt Squat", "Cuádriceps/Glúteo", "Máquina/Cinturón",
       ["Cinturón con peso.", "Sentadilla.",
        "Sin carga en columna."],
       ["Útil con problemas espalda", "Pierna pura"], "legs", "ultWZbUMPL8"),
    _g("le-trap-bar-deadlift", "Peso Muerto en Trap Bar", "Pierna/Espalda", "Trap Bar",
       ["De pie en trap bar.", "Levanta extendiendo cadera.",
        "Baja controlado."],
       ["Postura natural", "Cuádriceps + espalda"], "legs", "kI7H-V09bF8"),
    _g("le-elevacion-talones-pie", "Elevación de Talones de Pie", "Gemelos", "Máquina/Mancuernas",
       ["De pie con peso.", "Eleva talones.",
        "Baja completo."],
       ["Rango total", "Aprieta arriba"], "legs", "HkTuwSxnfcQ"),
    _g("le-elevacion-talones-sentado", "Elevación de Talones Sentado", "Gemelos (Sóleo)", "Máquina",
       ["Sentado en máquina específica.", "Eleva talones.", "Baja."],
       ["Sóleo dominante", "Repeticiones altas"], "legs", "JbyjNymZOt0"),
    _g("le-elevacion-talones-prensa", "Elevación Talones en Prensa", "Gemelos", "Prensa",
       ["En la prensa con pies sobre el borde.", "Eleva talones.",
        "Baja."],
       ["Pesos altos posibles", "Mucha activación"], "legs", "JbyjNymZOt0"),
    _g("le-donkey-calf-raise", "Donkey Calf Raise", "Gemelos", "Banco/Peso",
       ["Inclinado al frente.", "Compañero o peso encima.",
        "Eleva talones."],
       ["Variante old-school", "Gran rango"], "legs", "JbyjNymZOt0"),
    _g("le-jumping-jacks-pierna", "Jumping Jacks", "Pierna/Cardio", "Peso corporal",
       ["De pie con piernas juntas.", "Salta abriendo piernas y subiendo brazos.",
        "Vuelve y repite."],
       ["Calentamiento", "Cardio simple"], "cardio", "uLVt6u15L98"),
    _g("le-saltos-cajón", "Box Jumps (Saltos al Cajón)", "Pierna Explosiva", "Cajón pliométrico",
       ["De pie frente a cajón.", "Salta con ambos pies arriba.",
        "Baja andando."],
       ["Pliometría", "Aterriza suave"], "legs", "8Pq_IAPj5Hk"),
    _g("le-broad-jump", "Salto Largo (Broad Jump)", "Pierna Explosiva", "Peso corporal",
       ["Salto desde parado lo más lejos posible.", "Aterriza con rodillas semi-flexionadas."],
       ["Potencia explosiva", "Calentamiento"], "legs", "lU1QSKIu6gs"),
    _g("le-leg-press-cuadriceps", "Prensa Pies Bajos", "Cuádriceps", "Máquina",
       ["Pies bajos en plataforma de prensa.", "Baja flexionando.",
        "Empuja."],
       ["Cuádriceps dominante", "Cuidado rodillas"], "legs", "IZxyjW7MPJQ"),
    _g("le-leg-press-gluteo", "Prensa Pies Altos", "Glúteo/Femoral", "Máquina",
       ["Pies altos en plataforma.", "Baja flexionando.",
        "Empuja."],
       ["Glúteo + femoral", "Cuádriceps menos"], "legs", "IZxyjW7MPJQ"),
    _g("le-prensa-cerrada", "Prensa Pies Juntos", "Cuádriceps Externo", "Máquina",
       ["Pies juntos en plataforma.", "Sentadilla con prensa.", "Empuja."],
       ["Cuádriceps externo (vasto lateral)", "Variante específica"], "legs", "IZxyjW7MPJQ"),
    _g("le-prensa-abierta", "Prensa Pies Anchos", "Aductores/Glúteo", "Máquina",
       ["Pies muy anchos en plataforma.", "Sentadilla profunda.",
        "Empuja."],
       ["Aductores + glúteo", "Pies abiertos"], "legs", "IZxyjW7MPJQ"),
]

# ═══════════════════════════════════════════════════════════════
# GLÚTEOS — 18 ejercicios
# ═══════════════════════════════════════════════════════════════
GLUTEOS_FULL = [
    _g("gl-hip-thrust-barra", "Hip Thrust con Barra", "Glúteo", "Barra",
       ["Hombros en banco, barra sobre cadera.", "Pies hombros.",
        "Sube cadera apretando glúteos.", "Baja controlado."],
       ["REY del glúteo", "Aprieta arriba 1s"], "glutes", "xDmFkJxPzeM"),
    _g("gl-hip-thrust-mancuerna", "Hip Thrust con Mancuerna", "Glúteo", "Mancuerna",
       ["Hombros en banco, mancuerna en cadera.",
        "Sube apretando glúteos.", "Baja."],
       ["Versión sin barra", "Variante en casa"], "glutes", "xDmFkJxPzeM"),
    _g("gl-hip-thrust-1pierna", "Hip Thrust 1 Pierna", "Glúteo", "Banco",
       ["Hombros en banco, 1 pie en suelo.", "Otro elevado.",
        "Sube cadera con 1 pierna.", "Baja."],
       ["Unilateral brutal", "Equilibra glúteos"], "glutes", "xDmFkJxPzeM"),
    _g("gl-puente-gluteo", "Puente de Glúteos en Suelo", "Glúteo", "Peso corporal",
       ["Tumbado con rodillas flexionadas.", "Sube cadera apretando.",
        "Baja controlado."],
       ["Aprende activación glútea", "Sin equipo"], "glutes", "OUgsJ8-Vi0E"),
    _g("gl-puente-gluteo-disco", "Puente de Glúteos con Disco", "Glúteo", "Disco",
       ["Tumbado con disco en cadera.",
        "Sube apretando glúteos.", "Baja."],
       ["Carga progresiva", "Aprieta arriba"], "glutes", "OUgsJ8-Vi0E"),
    _g("gl-frog-pump", "Frog Pump", "Glúteo", "Peso corporal/Disco",
       ["Tumbado con plantas de pies juntas (rana).", "Sube cadera apretando.",
        "Baja."],
       ["Aísla glúteo", "Series de 30+"], "glutes", "OUgsJ8-Vi0E"),
    _g("gl-kickback-cable", "Glute Kickback en Polea", "Glúteo", "Polea",
       ["Polea baja, tobillera.", "Pierna estirada hacia atrás apretando.",
        "Vuelve."],
       ["Aísla glúteo medio/mayor", "Movimiento controlado"], "glutes", "iJW8Q-VhM7M"),
    _g("gl-kickback-maquina", "Glute Kickback en Máquina", "Glúteo", "Máquina",
       ["Sobre máquina específica.", "Empuja pie atrás.",
        "Vuelve."],
       ["Aislamiento puro", "Pesos altos posibles"], "glutes", "iJW8Q-VhM7M"),
    _g("gl-cable-pull-through", "Cable Pull-Through", "Glúteo/Femoral", "Polea",
       ["De espaldas a polea baja con cuerda entre piernas.", "Bisagra de cadera.",
        "Empuja con glúteos al subir."],
       ["Patrón de bisagra", "Glúteo + femoral"], "glutes", "DeXWQHCiH9c"),
    _g("gl-rdl-mancuerna", "Peso Muerto Rumano con Mancuernas", "Glúteo/Femoral", "Mancuernas",
       ["De pie con mancuernas.", "Bisagra empujando glúteo atrás.",
        "Baja a media tibia.", "Sube."],
       ["Femoral + glúteo", "Sin doblar espalda"], "glutes", "FQ-6acrlfXU"),
    _g("gl-rdl-1pierna", "Peso Muerto Rumano 1 Pierna", "Glúteo/Femoral/Equilibrio", "Mancuerna",
       ["1 mancuerna en mano contraria.", "Bisagra con 1 pierna mientras la otra extiende atrás.",
        "Vuelve."],
       ["Equilibrio + glúteo", "Avanzado"], "glutes", "Z3Yfey5sTIw"),
    _g("gl-clamshell", "Clamshell", "Glúteo Medio", "Banda elástica",
       ["Tumbado de lado con rodillas flexionadas.", "Banda en muslos.",
        "Abre la rodilla manteniendo pies juntos.", "Baja."],
       ["Glúteo medio aislado", "Activa antes de sentadillas"], "glutes", "g4_Q1Pra5gI"),
    _g("gl-fire-hydrant", "Fire Hydrant", "Glúteo Medio", "Peso corporal/Banda",
       ["A 4 patas.", "Levanta una pierna lateralmente como perro orinando.",
        "Vuelve."],
       ["Glúteo medio", "Aprieta arriba"], "glutes", "DZbaGifIQT0"),
    _g("gl-abductor-maquina", "Abductor en Máquina", "Glúteo Medio", "Máquina",
       ["Sentado en máquina específica.", "Abre piernas hacia afuera.",
        "Vuelve."],
       ["Glúteo medio aislado", "Pesos crecientes"], "glutes", "JzVwrn0EE5Q"),
    _g("gl-aductor-maquina", "Aductor en Máquina", "Aductores", "Máquina",
       ["Sentado en máquina específica.", "Junta piernas hacia centro.",
        "Vuelve."],
       ["Aductores", "Suele descuidarse"], "glutes", "JzVwrn0EE5Q"),
    _g("gl-sumo-deadlift", "Peso Muerto Sumo", "Glúteo/Aductor", "Barra",
       ["Pies muy anchos.", "Manos dentro de las piernas.",
        "Tira con glúteo y aductores."],
       ["Más glúteo que convencional", "Caderas abren"], "glutes", "wYREQkVtvEc"),
    _g("gl-sentadilla-sumo-mancuerna", "Sentadilla Sumo con Mancuerna", "Glúteo/Aductor", "Mancuerna",
       ["Pies muy abiertos.", "Mancuerna entre piernas.",
        "Sentadilla profunda apretando glúteos."],
       ["Variante glútea", "Aductores activados"], "glutes", "MeIiIdhvXT4"),
    _g("gl-walking-banda", "Caminata Lateral con Banda", "Glúteo Medio", "Banda elástica",
       ["Banda elástica en tobillos.", "Pasos laterales pequeños.",
        "Mantén tensión todo el tiempo."],
       ["Calentamiento glúteo medio", "Sin perder tensión"], "glutes", "h-RFOZ5MQXk"),
]

# ═══════════════════════════════════════════════════════════════
# CORE/ABDOMEN GYM — 20 nuevos ejercicios (categoría gym)
# ═══════════════════════════════════════════════════════════════
CORE_GYM_FULL = [
    _g("co-cable-crunch", "Crunch en Polea", "Abdomen", "Polea",
       ["De rodillas frente a polea alta.", "Cuerda en nuca.",
        "Crunch hacia el suelo contrayendo abdomen.", "Vuelve."],
       ["Carga progresiva", "Curva la espalda alta"], "core", "3qjoXDTuyOE"),
    _g("co-decline-situp", "Sit-up Declinado", "Abdomen", "Banco declinado",
       ["Banco declinado, pies asegurados.", "Manos cruzadas en pecho.",
        "Sube hasta vertical.", "Baja controlado."],
       ["Carga abdominal extra", "Sin tirar del cuello"], "core", "1fbU_MkV7NE"),
    _g("co-decline-reverse-crunch", "Crunch Invertido Declinado", "Abdomen Bajo", "Banco declinado",
       ["Banco declinado, manos sobre cabeza.", "Lleva rodillas al pecho.", "Baja."],
       ["Abdomen inferior", "Cuidado lumbar"], "core", "yVVwKipqASA"),
    _g("co-hanging-knee-raise", "Rodillas al Pecho Colgado", "Abdomen Bajo", "Barra",
       ["Cuélgate de la barra.", "Sube las rodillas al pecho.", "Baja controlado."],
       ["Sin balanceo", "Aguanta arriba"], "core", "ZGZ3dcpVcQE"),
    _g("co-hanging-leg-raise", "Piernas Rectas Colgado", "Abdomen Bajo", "Barra",
       ["Cuélgate.", "Sube piernas extendidas.", "Baja controlado."],
       ["Avanzado", "L-sit progresión"], "core", "Pr1ieGZ5atk"),
    _g("co-toes-to-bar", "Toes to Bar", "Abdomen", "Barra",
       ["Cuélgate.", "Sube los pies hasta tocar la barra.", "Baja."],
       ["Crossfit clásico", "Avanzado"], "core", "_03pCKOv4l4"),
    _g("co-windshield-wiper", "Limpiaparabrisas", "Oblicuos", "Esterilla",
       ["Tumbado, brazos en cruz.", "Piernas a 90º.",
        "Bájalas lado a lado controlando."],
       ["Oblicuos avanzado", "Despacio"], "core", "qmFjXzy5Z3M"),
    _g("co-dragon-flag", "Dragon Flag", "Core", "Banco",
       ["Tumbado en banco, sujétate detrás de la cabeza.",
        "Eleva todo el cuerpo recto.", "Baja despacio."],
       ["Avanzadísimo (Bruce Lee)", "Cuerpo recto"], "core", "PBhZsM05y6Y"),
    _g("co-l-sit", "L-Sit", "Core", "Paralelas",
       ["En paralelas o suelo.", "Piernas rectas formando L.", "Aguanta."],
       ["Aislamiento extremo", "5-10s"], "core", "IOY2pp2tQXI"),
    _g("co-ab-wheel", "Rueda Abdominal", "Core", "Rueda",
       ["De rodillas con rueda.", "Rueda hacia delante.", "Vuelve contrayendo."],
       ["Avanzado", "No arquees lumbar"], "core", "vM0HF5XqCMU"),
    _g("co-russian-twist-medicina", "Russian Twist con Pelota", "Oblicuos", "Pelota medicinal",
       ["Sentado, ligeramente reclinado.", "Pelota en manos.",
        "Rota torso lado a lado."],
       ["Oblicuos", "Pies despegados = más difícil"], "core", "wkD8rjkodUI"),
    _g("co-pallof-press-cable", "Pallof Press en Polea", "Core Anti-rotación", "Polea",
       ["De pie de lado a la polea.", "Empuja la cuerda al frente sin rotar.",
        "Aguanta y vuelve."],
       ["Anti-rotación", "Core funcional"], "core", "AH_QZLm_0-s"),
    _g("co-side-plank-cable", "Plancha Lateral con Polea", "Oblicuos", "Polea",
       ["Plancha lateral cerca de polea.", "Tira de la polea con la mano libre.",
        "Sin perder forma."],
       ["Oblicuos avanzado", "Estabilidad"], "core", "K2VljzCC16g"),
    _g("co-bicycle-crunch", "Bicicleta Abdominal", "Oblicuos", "Esterilla",
       ["Tumbado, manos en la nuca.", "Codo derecho a rodilla izquierda y alterna."],
       ["Oblicuos y recto", "Sin prisa"], "core", "9FGilxCbdz8"),
    _g("co-v-up", "V-Up", "Abdomen", "Esterilla",
       ["Tumbado, brazos y piernas extendidas.",
        "Eleva tronco y piernas tocando pies.", "Baja."],
       ["Recto abdominal completo", "Avanzado"], "core", "iP5UZf2arAQ"),
    _g("co-flutter-kicks", "Flutter Kicks", "Abdomen Bajo", "Esterilla",
       ["Tumbado.", "Eleva piernas ligeramente y patalea pequeño y rápido."],
       ["Abdomen inferior", "Lumbar pegada"], "core", "ANVdMDaYRts"),
    _g("co-mountain-climber", "Mountain Climbers", "Core/Cardio", "Peso corporal",
       ["Plancha alta.", "Lleva una rodilla al pecho alternando rápido."],
       ["Cardio + core", "Cadera estable"], "core", "nmwgirgXLYM"),
    _g("co-plank-weighted", "Plancha con Disco", "Core", "Disco",
       ["Plancha de antebrazos con disco en espalda baja.",
        "Aguanta tiempo objetivo."],
       ["Carga progresiva", "Cuerpo en línea"], "core", "ASdvN_XEl_c"),
    _g("co-side-plank-dip", "Plancha Lateral con Caída", "Oblicuos", "Esterilla",
       ["En plancha lateral.", "Baja la cadera al suelo y sube."],
       ["Oblicuos dinámico", "Controla la bajada"], "core", "K2VljzCC16g"),
    _g("co-cocoon", "Cocoon", "Abdomen", "Esterilla",
       ["Tumbado, brazos y piernas extendidas.",
        "Acerca rodillas al pecho y eleva tronco a la vez."],
       ["Compresión total", "Tipo V-up enrollado"], "core", "Nh99CxAImXg"),
]


# ═══════════════════════════════════════════════════════════════
# EXPORT — todos los ejercicios gym extendidos
# ═══════════════════════════════════════════════════════════════
GYM_FULL = (
    PECHO_FULL
    + ESPALDA_FULL
    + HOMBROS_FULL
    + BICEPS_FULL
    + TRICEPS_FULL
    + ANTEBRAZO_FULL
    + PIERNAS_FULL
    + GLUTEOS_FULL
    + CORE_GYM_FULL
)

